# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/whp/Desktop/Lucas/Vitis_Libraries-main/solver/L1/tests/ukf/vivado_bd/ukf_bd.srcs/sources_1/bd/design_1/ip/design_1_ukf0_0/design_1_ukf0_0.xci
# IP: The module: 'design_1_ukf0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/whp/Desktop/Lucas/Vitis_Libraries-main/solver/L1/tests/ukf/vivado_bd/ukf_bd.gen/sources_1/bd/design_1/ip/design_1_ukf0_0/constraints/ukf_accel_step_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ukf0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/whp/Desktop/Lucas/Vitis_Libraries-main/solver/L1/tests/ukf/vivado_bd/ukf_bd.srcs/sources_1/bd/design_1/ip/design_1_ukf0_0/design_1_ukf0_0.xci
# IP: The module: 'design_1_ukf0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/whp/Desktop/Lucas/Vitis_Libraries-main/solver/L1/tests/ukf/vivado_bd/ukf_bd.gen/sources_1/bd/design_1/ip/design_1_ukf0_0/constraints/ukf_accel_step_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ukf0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
