// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ukf_accel_step_ukf_ut_meas_3_2_Pipeline_VITIS_LOOP_259_16_VITIS_LOOP_260_17 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        S2_address0,
        S2_ce0,
        S2_we0,
        S2_d0,
        S2_1_address0,
        S2_1_ce0,
        S2_1_we0,
        S2_1_d0,
        Lmat_address0,
        Lmat_ce0,
        Lmat_q0,
        Lmat_5_address0,
        Lmat_5_ce0,
        Lmat_5_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] S2_address0;
output   S2_ce0;
output   S2_we0;
output  [31:0] S2_d0;
output  [0:0] S2_1_address0;
output   S2_1_ce0;
output   S2_1_we0;
output  [31:0] S2_1_d0;
output  [0:0] Lmat_address0;
output   Lmat_ce0;
input  [31:0] Lmat_q0;
output  [0:0] Lmat_5_address0;
output   Lmat_5_ce0;
input  [31:0] Lmat_5_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln259_fu_124_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] icmp_ln260_fu_143_p2;
reg   [0:0] icmp_ln260_reg_264;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] or_ln260_fu_173_p2;
reg   [0:0] or_ln260_reg_279;
wire   [63:0] zext_ln260_fu_161_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln259_fu_213_p1;
reg   [1:0] c0_fu_42;
wire   [1:0] select_ln260_1_fu_179_p3;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_c0_load;
reg   [1:0] r0_fu_46;
wire   [1:0] select_ln259_fu_206_p3;
reg   [2:0] indvar_flatten6_fu_50;
wire   [2:0] add_ln259_1_fu_130_p2;
reg   [2:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    Lmat_ce0_local;
reg    Lmat_5_ce0_local;
reg    S2_1_we0_local;
wire   [31:0] select_ln260_fu_225_p3;
reg    S2_1_ce0_local;
reg    S2_we0_local;
reg    S2_ce0_local;
wire   [0:0] trunc_ln259_fu_139_p1;
wire   [0:0] xor_ln259_fu_149_p2;
wire   [0:0] and_ln259_fu_155_p2;
wire   [0:0] xor_ln260_fu_167_p2;
wire   [1:0] add_ln259_fu_200_p2;
wire   [0:0] icmp_ln260_1_fu_219_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 c0_fu_42 = 2'd0;
#0 r0_fu_46 = 2'd0;
#0 indvar_flatten6_fu_50 = 3'd0;
#0 ap_done_reg = 1'b0;
end

ukf_accel_step_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln259_fu_124_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c0_fu_42 <= select_ln260_1_fu_179_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c0_fu_42 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln259_fu_124_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_50 <= add_ln259_1_fu_130_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_50 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            r0_fu_46 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            r0_fu_46 <= select_ln259_fu_206_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln260_reg_264 <= icmp_ln260_fu_143_p2;
        or_ln260_reg_279 <= or_ln260_fu_173_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Lmat_5_ce0_local = 1'b1;
    end else begin
        Lmat_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Lmat_ce0_local = 1'b1;
    end else begin
        Lmat_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S2_1_ce0_local = 1'b1;
    end else begin
        S2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln260_reg_279 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S2_1_we0_local = 1'b1;
    end else begin
        S2_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S2_ce0_local = 1'b1;
    end else begin
        S2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((or_ln260_reg_279 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S2_we0_local = 1'b1;
    end else begin
        S2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln259_fu_124_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c0_load = 2'd0;
    end else begin
        ap_sig_allocacmp_c0_load = c0_fu_42;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 3'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_50;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Lmat_5_address0 = zext_ln260_fu_161_p1;

assign Lmat_5_ce0 = Lmat_5_ce0_local;

assign Lmat_address0 = zext_ln260_fu_161_p1;

assign Lmat_ce0 = Lmat_ce0_local;

assign S2_1_address0 = zext_ln259_fu_213_p1;

assign S2_1_ce0 = S2_1_ce0_local;

assign S2_1_d0 = select_ln260_fu_225_p3;

assign S2_1_we0 = S2_1_we0_local;

assign S2_address0 = zext_ln259_fu_213_p1;

assign S2_ce0 = S2_ce0_local;

assign S2_d0 = select_ln260_fu_225_p3;

assign S2_we0 = S2_we0_local;

assign add_ln259_1_fu_130_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 3'd1);

assign add_ln259_fu_200_p2 = (r0_fu_46 + 2'd1);

assign and_ln259_fu_155_p2 = (xor_ln259_fu_149_p2 & trunc_ln259_fu_139_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln259_fu_124_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln260_1_fu_219_p2 = ((select_ln259_fu_206_p3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln260_fu_143_p2 = ((ap_sig_allocacmp_c0_load == 2'd2) ? 1'b1 : 1'b0);

assign or_ln260_fu_173_p2 = (xor_ln260_fu_167_p2 | icmp_ln260_fu_143_p2);

assign select_ln259_fu_206_p3 = ((icmp_ln260_reg_264[0:0] == 1'b1) ? add_ln259_fu_200_p2 : r0_fu_46);

assign select_ln260_1_fu_179_p3 = ((and_ln259_fu_155_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln260_fu_225_p3 = ((icmp_ln260_1_fu_219_p2[0:0] == 1'b1) ? Lmat_5_q0 : Lmat_q0);

assign trunc_ln259_fu_139_p1 = ap_sig_allocacmp_c0_load[0:0];

assign xor_ln259_fu_149_p2 = (icmp_ln260_fu_143_p2 ^ 1'd1);

assign xor_ln260_fu_167_p2 = (trunc_ln259_fu_139_p1 ^ 1'd1);

assign zext_ln259_fu_213_p1 = select_ln259_fu_206_p3;

assign zext_ln260_fu_161_p1 = and_ln259_fu_155_p2;

endmodule //ukf_accel_step_ukf_ut_meas_3_2_Pipeline_VITIS_LOOP_259_16_VITIS_LOOP_260_17
