// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ukf_accel_step_ukf_ut_meas_3_2_Pipeline_VITIS_LOOP_240_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mux_case_01_i_reload,
        mux_case_15_i_reload,
        mux_case_28_i_reload,
        mux_case_311_i_reload,
        mux_case_415_i_reload,
        mux_case_519_i_reload,
        mux_case_623_i_reload,
        p_reload,
        mux_case_0926_i_reload,
        mux_case_11029_i_reload,
        mux_case_21132_i_reload,
        mux_case_31235_i_reload,
        mux_case_41338_i_reload,
        mux_case_51441_i_reload,
        mux_case_61544_i_reload,
        add_119_i_reload,
        Z2_13_load_out,
        Z2_13_load_out_ap_vld,
        Z2_12_load_out,
        Z2_12_load_out_ap_vld,
        Z2_11_load_out,
        Z2_11_load_out_ap_vld,
        Z2_10_load_out,
        Z2_10_load_out_ap_vld,
        Z2_9_load_out,
        Z2_9_load_out_ap_vld,
        Z2_8_load_out,
        Z2_8_load_out_ap_vld,
        Z2_7_load_out,
        Z2_7_load_out_ap_vld,
        Z2_6_load_out,
        Z2_6_load_out_ap_vld,
        Z2_5_load_out,
        Z2_5_load_out_ap_vld,
        Z2_4_load_out,
        Z2_4_load_out_ap_vld,
        Z2_3_load_out,
        Z2_3_load_out_ap_vld,
        Z2_2_load_out,
        Z2_2_load_out_ap_vld,
        Z2_1_load_out,
        Z2_1_load_out_ap_vld,
        Z2_load_out,
        Z2_load_out_ap_vld,
        grp_fu_631_p_din0,
        grp_fu_631_p_din1,
        grp_fu_631_p_opcode,
        grp_fu_631_p_dout0,
        grp_fu_631_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] mux_case_01_i_reload;
input  [31:0] mux_case_15_i_reload;
input  [31:0] mux_case_28_i_reload;
input  [31:0] mux_case_311_i_reload;
input  [31:0] mux_case_415_i_reload;
input  [31:0] mux_case_519_i_reload;
input  [31:0] mux_case_623_i_reload;
input  [31:0] p_reload;
input  [31:0] mux_case_0926_i_reload;
input  [31:0] mux_case_11029_i_reload;
input  [31:0] mux_case_21132_i_reload;
input  [31:0] mux_case_31235_i_reload;
input  [31:0] mux_case_41338_i_reload;
input  [31:0] mux_case_51441_i_reload;
input  [31:0] mux_case_61544_i_reload;
input  [31:0] add_119_i_reload;
output  [31:0] Z2_13_load_out;
output   Z2_13_load_out_ap_vld;
output  [31:0] Z2_12_load_out;
output   Z2_12_load_out_ap_vld;
output  [31:0] Z2_11_load_out;
output   Z2_11_load_out_ap_vld;
output  [31:0] Z2_10_load_out;
output   Z2_10_load_out_ap_vld;
output  [31:0] Z2_9_load_out;
output   Z2_9_load_out_ap_vld;
output  [31:0] Z2_8_load_out;
output   Z2_8_load_out_ap_vld;
output  [31:0] Z2_7_load_out;
output   Z2_7_load_out_ap_vld;
output  [31:0] Z2_6_load_out;
output   Z2_6_load_out_ap_vld;
output  [31:0] Z2_5_load_out;
output   Z2_5_load_out_ap_vld;
output  [31:0] Z2_4_load_out;
output   Z2_4_load_out_ap_vld;
output  [31:0] Z2_3_load_out;
output   Z2_3_load_out_ap_vld;
output  [31:0] Z2_2_load_out;
output   Z2_2_load_out_ap_vld;
output  [31:0] Z2_1_load_out;
output   Z2_1_load_out_ap_vld;
output  [31:0] Z2_load_out;
output   Z2_load_out_ap_vld;
output  [31:0] grp_fu_631_p_din0;
output  [31:0] grp_fu_631_p_din1;
output  [0:0] grp_fu_631_p_opcode;
input  [31:0] grp_fu_631_p_dout0;
output   grp_fu_631_p_ce;

reg ap_idle;
reg Z2_13_load_out_ap_vld;
reg Z2_12_load_out_ap_vld;
reg Z2_11_load_out_ap_vld;
reg Z2_10_load_out_ap_vld;
reg Z2_9_load_out_ap_vld;
reg Z2_8_load_out_ap_vld;
reg Z2_7_load_out_ap_vld;
reg Z2_6_load_out_ap_vld;
reg Z2_5_load_out_ap_vld;
reg Z2_4_load_out_ap_vld;
reg Z2_3_load_out_ap_vld;
reg Z2_2_load_out_ap_vld;
reg Z2_1_load_out_ap_vld;
reg Z2_load_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln240_fu_372_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [2:0] k_5_reg_688;
reg   [2:0] k_5_reg_688_pp0_iter1_reg;
reg   [2:0] k_5_reg_688_pp0_iter2_reg;
reg   [2:0] k_5_reg_688_pp0_iter3_reg;
reg   [2:0] k_5_reg_688_pp0_iter4_reg;
reg   [0:0] icmp_ln240_reg_692;
reg   [0:0] icmp_ln240_reg_692_pp0_iter1_reg;
reg   [0:0] icmp_ln240_reg_692_pp0_iter2_reg;
reg   [0:0] icmp_ln240_reg_692_pp0_iter3_reg;
wire   [31:0] tmp_17_i_fu_384_p17;
reg   [31:0] tmp_17_i_reg_696;
wire   [31:0] tmp_18_i_fu_420_p17;
reg   [31:0] tmp_18_i_reg_701;
reg   [2:0] k_fu_102;
wire   [2:0] add_ln240_fu_378_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_k_5;
wire    ap_block_pp0_stage0;
reg   [31:0] Z2_fu_106;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [31:0] Z2_1_fu_110;
wire   [31:0] grp_fu_360_p2;
reg   [31:0] Z2_2_fu_114;
reg   [31:0] Z2_3_fu_118;
reg   [31:0] Z2_4_fu_122;
reg   [31:0] Z2_5_fu_126;
reg   [31:0] Z2_6_fu_130;
reg   [31:0] Z2_7_fu_134;
reg   [31:0] Z2_8_fu_138;
reg   [31:0] Z2_9_fu_142;
reg   [31:0] Z2_10_fu_146;
reg   [31:0] Z2_11_fu_150;
reg   [31:0] Z2_12_fu_154;
reg   [31:0] Z2_13_fu_158;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] tmp_17_i_fu_384_p15;
wire   [31:0] tmp_18_i_fu_420_p15;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_17_i_fu_384_p1;
wire   [2:0] tmp_17_i_fu_384_p3;
wire   [2:0] tmp_17_i_fu_384_p5;
wire   [2:0] tmp_17_i_fu_384_p7;
wire  signed [2:0] tmp_17_i_fu_384_p9;
wire  signed [2:0] tmp_17_i_fu_384_p11;
wire  signed [2:0] tmp_17_i_fu_384_p13;
wire   [2:0] tmp_18_i_fu_420_p1;
wire   [2:0] tmp_18_i_fu_420_p3;
wire   [2:0] tmp_18_i_fu_420_p5;
wire   [2:0] tmp_18_i_fu_420_p7;
wire  signed [2:0] tmp_18_i_fu_420_p9;
wire  signed [2:0] tmp_18_i_fu_420_p11;
wire  signed [2:0] tmp_18_i_fu_420_p13;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 k_fu_102 = 3'd0;
#0 Z2_fu_106 = 32'd0;
#0 Z2_1_fu_110 = 32'd0;
#0 Z2_2_fu_114 = 32'd0;
#0 Z2_3_fu_118 = 32'd0;
#0 Z2_4_fu_122 = 32'd0;
#0 Z2_5_fu_126 = 32'd0;
#0 Z2_6_fu_130 = 32'd0;
#0 Z2_7_fu_134 = 32'd0;
#0 Z2_8_fu_138 = 32'd0;
#0 Z2_9_fu_142 = 32'd0;
#0 Z2_10_fu_146 = 32'd0;
#0 Z2_11_fu_150 = 32'd0;
#0 Z2_12_fu_154 = 32'd0;
#0 Z2_13_fu_158 = 32'd0;
#0 ap_done_reg = 1'b0;
end

ukf_accel_step_fsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_5_full_dsp_1_U334(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_18_i_reg_701),
    .din1(add_119_i_reload),
    .ce(1'b1),
    .dout(grp_fu_360_p2)
);

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_15_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_15_3_32_1_1_U335(
    .din0(mux_case_01_i_reload),
    .din1(mux_case_15_i_reload),
    .din2(mux_case_28_i_reload),
    .din3(mux_case_311_i_reload),
    .din4(mux_case_415_i_reload),
    .din5(mux_case_519_i_reload),
    .din6(mux_case_623_i_reload),
    .def(tmp_17_i_fu_384_p15),
    .sel(ap_sig_allocacmp_k_5),
    .dout(tmp_17_i_fu_384_p17)
);

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_15_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_15_3_32_1_1_U336(
    .din0(mux_case_0926_i_reload),
    .din1(mux_case_11029_i_reload),
    .din2(mux_case_21132_i_reload),
    .din3(mux_case_31235_i_reload),
    .din4(mux_case_41338_i_reload),
    .din5(mux_case_51441_i_reload),
    .din6(mux_case_61544_i_reload),
    .def(tmp_18_i_fu_420_p15),
    .sel(ap_sig_allocacmp_k_5),
    .dout(tmp_18_i_fu_420_p17)
);

ukf_accel_step_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln240_fu_372_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_102 <= add_ln240_fu_378_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_102 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (k_5_reg_688_pp0_iter4_reg == 3'd5))) begin
        Z2_10_fu_146 <= grp_fu_631_p_dout0;
        Z2_11_fu_150 <= grp_fu_360_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & ((k_5_reg_688_pp0_iter4_reg == 3'd6) | (k_5_reg_688_pp0_iter4_reg == 3'd7)))) begin
        Z2_12_fu_154 <= grp_fu_631_p_dout0;
        Z2_13_fu_158 <= grp_fu_360_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (k_5_reg_688_pp0_iter4_reg == 3'd0))) begin
        Z2_1_fu_110 <= grp_fu_360_p2;
        Z2_fu_106 <= grp_fu_631_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (k_5_reg_688_pp0_iter4_reg == 3'd1))) begin
        Z2_2_fu_114 <= grp_fu_631_p_dout0;
        Z2_3_fu_118 <= grp_fu_360_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (k_5_reg_688_pp0_iter4_reg == 3'd2))) begin
        Z2_4_fu_122 <= grp_fu_631_p_dout0;
        Z2_5_fu_126 <= grp_fu_360_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (k_5_reg_688_pp0_iter4_reg == 3'd3))) begin
        Z2_6_fu_130 <= grp_fu_631_p_dout0;
        Z2_7_fu_134 <= grp_fu_360_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (k_5_reg_688_pp0_iter4_reg == 3'd4))) begin
        Z2_8_fu_138 <= grp_fu_631_p_dout0;
        Z2_9_fu_142 <= grp_fu_360_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln240_reg_692 <= icmp_ln240_fu_372_p2;
        icmp_ln240_reg_692_pp0_iter1_reg <= icmp_ln240_reg_692;
        k_5_reg_688 <= ap_sig_allocacmp_k_5;
        k_5_reg_688_pp0_iter1_reg <= k_5_reg_688;
        tmp_17_i_reg_696 <= tmp_17_i_fu_384_p17;
        tmp_18_i_reg_701 <= tmp_18_i_fu_420_p17;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln240_reg_692_pp0_iter2_reg <= icmp_ln240_reg_692_pp0_iter1_reg;
        icmp_ln240_reg_692_pp0_iter3_reg <= icmp_ln240_reg_692_pp0_iter2_reg;
        k_5_reg_688_pp0_iter2_reg <= k_5_reg_688_pp0_iter1_reg;
        k_5_reg_688_pp0_iter3_reg <= k_5_reg_688_pp0_iter2_reg;
        k_5_reg_688_pp0_iter4_reg <= k_5_reg_688_pp0_iter3_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_10_load_out_ap_vld = 1'b1;
    end else begin
        Z2_10_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_11_load_out_ap_vld = 1'b1;
    end else begin
        Z2_11_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_12_load_out_ap_vld = 1'b1;
    end else begin
        Z2_12_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_13_load_out_ap_vld = 1'b1;
    end else begin
        Z2_13_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_1_load_out_ap_vld = 1'b1;
    end else begin
        Z2_1_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_2_load_out_ap_vld = 1'b1;
    end else begin
        Z2_2_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_3_load_out_ap_vld = 1'b1;
    end else begin
        Z2_3_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_4_load_out_ap_vld = 1'b1;
    end else begin
        Z2_4_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_5_load_out_ap_vld = 1'b1;
    end else begin
        Z2_5_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_6_load_out_ap_vld = 1'b1;
    end else begin
        Z2_6_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_7_load_out_ap_vld = 1'b1;
    end else begin
        Z2_7_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_8_load_out_ap_vld = 1'b1;
    end else begin
        Z2_8_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_9_load_out_ap_vld = 1'b1;
    end else begin
        Z2_9_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln240_reg_692_pp0_iter3_reg == 1'd1))) begin
        Z2_load_out_ap_vld = 1'b1;
    end else begin
        Z2_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln240_fu_372_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_5 = 3'd0;
    end else begin
        ap_sig_allocacmp_k_5 = k_fu_102;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Z2_10_load_out = Z2_10_fu_146;

assign Z2_11_load_out = Z2_11_fu_150;

assign Z2_12_load_out = Z2_12_fu_154;

assign Z2_13_load_out = Z2_13_fu_158;

assign Z2_1_load_out = Z2_1_fu_110;

assign Z2_2_load_out = Z2_2_fu_114;

assign Z2_3_load_out = Z2_3_fu_118;

assign Z2_4_load_out = Z2_4_fu_122;

assign Z2_5_load_out = Z2_5_fu_126;

assign Z2_6_load_out = Z2_6_fu_130;

assign Z2_7_load_out = Z2_7_fu_134;

assign Z2_8_load_out = Z2_8_fu_138;

assign Z2_9_load_out = Z2_9_fu_142;

assign Z2_load_out = Z2_fu_106;

assign add_ln240_fu_378_p2 = (ap_sig_allocacmp_k_5 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_631_p_ce = 1'b1;

assign grp_fu_631_p_din0 = tmp_17_i_reg_696;

assign grp_fu_631_p_din1 = p_reload;

assign grp_fu_631_p_opcode = 2'd1;

assign icmp_ln240_fu_372_p2 = ((ap_sig_allocacmp_k_5 == 3'd7) ? 1'b1 : 1'b0);

assign tmp_17_i_fu_384_p15 = 'bx;

assign tmp_18_i_fu_420_p15 = 'bx;

endmodule //ukf_accel_step_ukf_ut_meas_3_2_Pipeline_VITIS_LOOP_240_7
