// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ukf_accel_step_ukf_ut_process_3_2_Pipeline_VITIS_LOOP_197_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mux_case_01_i_i_reload,
        mux_case_15_i_i_reload,
        mux_case_28_i_i_reload,
        mux_case_311_i_i_reload,
        mux_case_414_i_i_reload,
        mux_case_517_i_i_reload,
        mux_case_622_i_i_reload,
        p_reload,
        mux_case_01525_i_i_reload,
        mux_case_11628_i_i_reload,
        mux_case_21731_i_i_reload,
        mux_case_31834_i_i_reload,
        mux_case_41937_i_i_reload,
        mux_case_52040_i_i_reload,
        mux_case_62143_i_i_reload,
        add_116_i_i_reload,
        mux_case_02246_i_i_reload,
        mux_case_12349_i_i_reload,
        mux_case_22452_i_i_reload,
        mux_case_32555_i_i_reload,
        mux_case_42658_i_i_reload,
        mux_case_52761_i_i_reload,
        mux_case_62864_i_i_reload,
        add_218_i_i_reload,
        X2_20_load_out,
        X2_20_load_out_ap_vld,
        X2_19_load_out,
        X2_19_load_out_ap_vld,
        X2_18_load_out,
        X2_18_load_out_ap_vld,
        X2_17_load_out,
        X2_17_load_out_ap_vld,
        X2_16_load_out,
        X2_16_load_out_ap_vld,
        X2_15_load_out,
        X2_15_load_out_ap_vld,
        X2_14_load_out,
        X2_14_load_out_ap_vld,
        X2_13_load_out,
        X2_13_load_out_ap_vld,
        X2_12_load_out,
        X2_12_load_out_ap_vld,
        X2_11_load_out,
        X2_11_load_out_ap_vld,
        X2_10_load_out,
        X2_10_load_out_ap_vld,
        X2_9_load_out,
        X2_9_load_out_ap_vld,
        X2_8_load_out,
        X2_8_load_out_ap_vld,
        X2_7_load_out,
        X2_7_load_out_ap_vld,
        X2_6_load_out,
        X2_6_load_out_ap_vld,
        X2_5_load_out,
        X2_5_load_out_ap_vld,
        X2_4_load_out,
        X2_4_load_out_ap_vld,
        X2_3_load_out,
        X2_3_load_out_ap_vld,
        X2_2_load_out,
        X2_2_load_out_ap_vld,
        X2_1_load_out,
        X2_1_load_out_ap_vld,
        X2_load_out,
        X2_load_out_ap_vld,
        grp_fu_1043_p_din0,
        grp_fu_1043_p_din1,
        grp_fu_1043_p_opcode,
        grp_fu_1043_p_dout0,
        grp_fu_1043_p_ce,
        grp_fu_1048_p_din0,
        grp_fu_1048_p_din1,
        grp_fu_1048_p_opcode,
        grp_fu_1048_p_dout0,
        grp_fu_1048_p_ce,
        grp_fu_2613_p_din0,
        grp_fu_2613_p_din1,
        grp_fu_2613_p_opcode,
        grp_fu_2613_p_dout0,
        grp_fu_2613_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] mux_case_01_i_i_reload;
input  [31:0] mux_case_15_i_i_reload;
input  [31:0] mux_case_28_i_i_reload;
input  [31:0] mux_case_311_i_i_reload;
input  [31:0] mux_case_414_i_i_reload;
input  [31:0] mux_case_517_i_i_reload;
input  [31:0] mux_case_622_i_i_reload;
input  [31:0] p_reload;
input  [31:0] mux_case_01525_i_i_reload;
input  [31:0] mux_case_11628_i_i_reload;
input  [31:0] mux_case_21731_i_i_reload;
input  [31:0] mux_case_31834_i_i_reload;
input  [31:0] mux_case_41937_i_i_reload;
input  [31:0] mux_case_52040_i_i_reload;
input  [31:0] mux_case_62143_i_i_reload;
input  [31:0] add_116_i_i_reload;
input  [31:0] mux_case_02246_i_i_reload;
input  [31:0] mux_case_12349_i_i_reload;
input  [31:0] mux_case_22452_i_i_reload;
input  [31:0] mux_case_32555_i_i_reload;
input  [31:0] mux_case_42658_i_i_reload;
input  [31:0] mux_case_52761_i_i_reload;
input  [31:0] mux_case_62864_i_i_reload;
input  [31:0] add_218_i_i_reload;
output  [31:0] X2_20_load_out;
output   X2_20_load_out_ap_vld;
output  [31:0] X2_19_load_out;
output   X2_19_load_out_ap_vld;
output  [31:0] X2_18_load_out;
output   X2_18_load_out_ap_vld;
output  [31:0] X2_17_load_out;
output   X2_17_load_out_ap_vld;
output  [31:0] X2_16_load_out;
output   X2_16_load_out_ap_vld;
output  [31:0] X2_15_load_out;
output   X2_15_load_out_ap_vld;
output  [31:0] X2_14_load_out;
output   X2_14_load_out_ap_vld;
output  [31:0] X2_13_load_out;
output   X2_13_load_out_ap_vld;
output  [31:0] X2_12_load_out;
output   X2_12_load_out_ap_vld;
output  [31:0] X2_11_load_out;
output   X2_11_load_out_ap_vld;
output  [31:0] X2_10_load_out;
output   X2_10_load_out_ap_vld;
output  [31:0] X2_9_load_out;
output   X2_9_load_out_ap_vld;
output  [31:0] X2_8_load_out;
output   X2_8_load_out_ap_vld;
output  [31:0] X2_7_load_out;
output   X2_7_load_out_ap_vld;
output  [31:0] X2_6_load_out;
output   X2_6_load_out_ap_vld;
output  [31:0] X2_5_load_out;
output   X2_5_load_out_ap_vld;
output  [31:0] X2_4_load_out;
output   X2_4_load_out_ap_vld;
output  [31:0] X2_3_load_out;
output   X2_3_load_out_ap_vld;
output  [31:0] X2_2_load_out;
output   X2_2_load_out_ap_vld;
output  [31:0] X2_1_load_out;
output   X2_1_load_out_ap_vld;
output  [31:0] X2_load_out;
output   X2_load_out_ap_vld;
output  [31:0] grp_fu_1043_p_din0;
output  [31:0] grp_fu_1043_p_din1;
output  [0:0] grp_fu_1043_p_opcode;
input  [31:0] grp_fu_1043_p_dout0;
output   grp_fu_1043_p_ce;
output  [31:0] grp_fu_1048_p_din0;
output  [31:0] grp_fu_1048_p_din1;
output  [0:0] grp_fu_1048_p_opcode;
input  [31:0] grp_fu_1048_p_dout0;
output   grp_fu_1048_p_ce;
output  [31:0] grp_fu_2613_p_din0;
output  [31:0] grp_fu_2613_p_din1;
output  [0:0] grp_fu_2613_p_opcode;
input  [31:0] grp_fu_2613_p_dout0;
output   grp_fu_2613_p_ce;

reg ap_idle;
reg X2_20_load_out_ap_vld;
reg X2_19_load_out_ap_vld;
reg X2_18_load_out_ap_vld;
reg X2_17_load_out_ap_vld;
reg X2_16_load_out_ap_vld;
reg X2_15_load_out_ap_vld;
reg X2_14_load_out_ap_vld;
reg X2_13_load_out_ap_vld;
reg X2_12_load_out_ap_vld;
reg X2_11_load_out_ap_vld;
reg X2_10_load_out_ap_vld;
reg X2_9_load_out_ap_vld;
reg X2_8_load_out_ap_vld;
reg X2_7_load_out_ap_vld;
reg X2_6_load_out_ap_vld;
reg X2_5_load_out_ap_vld;
reg X2_4_load_out_ap_vld;
reg X2_3_load_out_ap_vld;
reg X2_2_load_out_ap_vld;
reg X2_1_load_out_ap_vld;
reg X2_load_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln197_fu_531_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [2:0] k_reg_993;
reg   [2:0] k_reg_993_pp0_iter1_reg;
reg   [2:0] k_reg_993_pp0_iter2_reg;
reg   [2:0] k_reg_993_pp0_iter3_reg;
reg   [2:0] k_reg_993_pp0_iter4_reg;
reg   [0:0] icmp_ln197_reg_997;
reg   [0:0] icmp_ln197_reg_997_pp0_iter1_reg;
reg   [0:0] icmp_ln197_reg_997_pp0_iter2_reg;
reg   [0:0] icmp_ln197_reg_997_pp0_iter3_reg;
wire   [31:0] tmp_6_i_fu_543_p17;
reg   [31:0] tmp_6_i_reg_1001;
wire   [31:0] tmp_7_i_fu_579_p17;
reg   [31:0] tmp_7_i_reg_1006;
wire   [31:0] tmp_8_i_fu_615_p17;
reg   [31:0] tmp_8_i_reg_1011;
reg   [2:0] k_2_fu_132;
wire   [2:0] add_ln197_fu_537_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_k;
wire    ap_block_pp0_stage0;
reg   [31:0] X2_fu_136;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [31:0] X2_1_fu_140;
reg   [31:0] X2_2_fu_144;
reg   [31:0] X2_3_fu_148;
reg   [31:0] X2_4_fu_152;
reg   [31:0] X2_5_fu_156;
reg   [31:0] X2_6_fu_160;
reg   [31:0] X2_7_fu_164;
reg   [31:0] X2_8_fu_168;
reg   [31:0] X2_9_fu_172;
reg   [31:0] X2_10_fu_176;
reg   [31:0] X2_11_fu_180;
reg   [31:0] X2_12_fu_184;
reg   [31:0] X2_13_fu_188;
reg   [31:0] X2_14_fu_192;
reg   [31:0] X2_15_fu_196;
reg   [31:0] X2_16_fu_200;
reg   [31:0] X2_17_fu_204;
reg   [31:0] X2_18_fu_208;
reg   [31:0] X2_19_fu_212;
reg   [31:0] X2_20_fu_216;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] tmp_6_i_fu_543_p15;
wire   [31:0] tmp_7_i_fu_579_p15;
wire   [31:0] tmp_8_i_fu_615_p15;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_6_i_fu_543_p1;
wire   [2:0] tmp_6_i_fu_543_p3;
wire   [2:0] tmp_6_i_fu_543_p5;
wire   [2:0] tmp_6_i_fu_543_p7;
wire  signed [2:0] tmp_6_i_fu_543_p9;
wire  signed [2:0] tmp_6_i_fu_543_p11;
wire  signed [2:0] tmp_6_i_fu_543_p13;
wire   [2:0] tmp_7_i_fu_579_p1;
wire   [2:0] tmp_7_i_fu_579_p3;
wire   [2:0] tmp_7_i_fu_579_p5;
wire   [2:0] tmp_7_i_fu_579_p7;
wire  signed [2:0] tmp_7_i_fu_579_p9;
wire  signed [2:0] tmp_7_i_fu_579_p11;
wire  signed [2:0] tmp_7_i_fu_579_p13;
wire   [2:0] tmp_8_i_fu_615_p1;
wire   [2:0] tmp_8_i_fu_615_p3;
wire   [2:0] tmp_8_i_fu_615_p5;
wire   [2:0] tmp_8_i_fu_615_p7;
wire  signed [2:0] tmp_8_i_fu_615_p9;
wire  signed [2:0] tmp_8_i_fu_615_p11;
wire  signed [2:0] tmp_8_i_fu_615_p13;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 k_2_fu_132 = 3'd0;
#0 X2_fu_136 = 32'd0;
#0 X2_1_fu_140 = 32'd0;
#0 X2_2_fu_144 = 32'd0;
#0 X2_3_fu_148 = 32'd0;
#0 X2_4_fu_152 = 32'd0;
#0 X2_5_fu_156 = 32'd0;
#0 X2_6_fu_160 = 32'd0;
#0 X2_7_fu_164 = 32'd0;
#0 X2_8_fu_168 = 32'd0;
#0 X2_9_fu_172 = 32'd0;
#0 X2_10_fu_176 = 32'd0;
#0 X2_11_fu_180 = 32'd0;
#0 X2_12_fu_184 = 32'd0;
#0 X2_13_fu_188 = 32'd0;
#0 X2_14_fu_192 = 32'd0;
#0 X2_15_fu_196 = 32'd0;
#0 X2_16_fu_200 = 32'd0;
#0 X2_17_fu_204 = 32'd0;
#0 X2_18_fu_208 = 32'd0;
#0 X2_19_fu_212 = 32'd0;
#0 X2_20_fu_216 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_15_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_15_3_32_1_1_U101(
    .din0(mux_case_01_i_i_reload),
    .din1(mux_case_15_i_i_reload),
    .din2(mux_case_28_i_i_reload),
    .din3(mux_case_311_i_i_reload),
    .din4(mux_case_414_i_i_reload),
    .din5(mux_case_517_i_i_reload),
    .din6(mux_case_622_i_i_reload),
    .def(tmp_6_i_fu_543_p15),
    .sel(ap_sig_allocacmp_k),
    .dout(tmp_6_i_fu_543_p17)
);

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_15_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_15_3_32_1_1_U102(
    .din0(mux_case_01525_i_i_reload),
    .din1(mux_case_11628_i_i_reload),
    .din2(mux_case_21731_i_i_reload),
    .din3(mux_case_31834_i_i_reload),
    .din4(mux_case_41937_i_i_reload),
    .din5(mux_case_52040_i_i_reload),
    .din6(mux_case_62143_i_i_reload),
    .def(tmp_7_i_fu_579_p15),
    .sel(ap_sig_allocacmp_k),
    .dout(tmp_7_i_fu_579_p17)
);

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_15_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_15_3_32_1_1_U103(
    .din0(mux_case_02246_i_i_reload),
    .din1(mux_case_12349_i_i_reload),
    .din2(mux_case_22452_i_i_reload),
    .din3(mux_case_32555_i_i_reload),
    .din4(mux_case_42658_i_i_reload),
    .din5(mux_case_52761_i_i_reload),
    .din6(mux_case_62864_i_i_reload),
    .def(tmp_8_i_fu_615_p15),
    .sel(ap_sig_allocacmp_k),
    .dout(tmp_8_i_fu_615_p17)
);

ukf_accel_step_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln197_fu_531_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_2_fu_132 <= add_ln197_fu_537_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_2_fu_132 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (k_reg_993_pp0_iter4_reg == 3'd3))) begin
        X2_10_fu_176 <= grp_fu_1048_p_dout0;
        X2_11_fu_180 <= grp_fu_2613_p_dout0;
        X2_9_fu_172 <= grp_fu_1043_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (k_reg_993_pp0_iter4_reg == 3'd4))) begin
        X2_12_fu_184 <= grp_fu_1043_p_dout0;
        X2_13_fu_188 <= grp_fu_1048_p_dout0;
        X2_14_fu_192 <= grp_fu_2613_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (k_reg_993_pp0_iter4_reg == 3'd5))) begin
        X2_15_fu_196 <= grp_fu_1043_p_dout0;
        X2_16_fu_200 <= grp_fu_1048_p_dout0;
        X2_17_fu_204 <= grp_fu_2613_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & ((k_reg_993_pp0_iter4_reg == 3'd6) | (k_reg_993_pp0_iter4_reg == 3'd7)))) begin
        X2_18_fu_208 <= grp_fu_1043_p_dout0;
        X2_19_fu_212 <= grp_fu_1048_p_dout0;
        X2_20_fu_216 <= grp_fu_2613_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (k_reg_993_pp0_iter4_reg == 3'd0))) begin
        X2_1_fu_140 <= grp_fu_1048_p_dout0;
        X2_2_fu_144 <= grp_fu_2613_p_dout0;
        X2_fu_136 <= grp_fu_1043_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (k_reg_993_pp0_iter4_reg == 3'd1))) begin
        X2_3_fu_148 <= grp_fu_1043_p_dout0;
        X2_4_fu_152 <= grp_fu_1048_p_dout0;
        X2_5_fu_156 <= grp_fu_2613_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (k_reg_993_pp0_iter4_reg == 3'd2))) begin
        X2_6_fu_160 <= grp_fu_1043_p_dout0;
        X2_7_fu_164 <= grp_fu_1048_p_dout0;
        X2_8_fu_168 <= grp_fu_2613_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln197_reg_997 <= icmp_ln197_fu_531_p2;
        icmp_ln197_reg_997_pp0_iter1_reg <= icmp_ln197_reg_997;
        k_reg_993 <= ap_sig_allocacmp_k;
        k_reg_993_pp0_iter1_reg <= k_reg_993;
        tmp_6_i_reg_1001 <= tmp_6_i_fu_543_p17;
        tmp_7_i_reg_1006 <= tmp_7_i_fu_579_p17;
        tmp_8_i_reg_1011 <= tmp_8_i_fu_615_p17;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln197_reg_997_pp0_iter2_reg <= icmp_ln197_reg_997_pp0_iter1_reg;
        icmp_ln197_reg_997_pp0_iter3_reg <= icmp_ln197_reg_997_pp0_iter2_reg;
        k_reg_993_pp0_iter2_reg <= k_reg_993_pp0_iter1_reg;
        k_reg_993_pp0_iter3_reg <= k_reg_993_pp0_iter2_reg;
        k_reg_993_pp0_iter4_reg <= k_reg_993_pp0_iter3_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_10_load_out_ap_vld = 1'b1;
    end else begin
        X2_10_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_11_load_out_ap_vld = 1'b1;
    end else begin
        X2_11_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_12_load_out_ap_vld = 1'b1;
    end else begin
        X2_12_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_13_load_out_ap_vld = 1'b1;
    end else begin
        X2_13_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_14_load_out_ap_vld = 1'b1;
    end else begin
        X2_14_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_15_load_out_ap_vld = 1'b1;
    end else begin
        X2_15_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_16_load_out_ap_vld = 1'b1;
    end else begin
        X2_16_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_17_load_out_ap_vld = 1'b1;
    end else begin
        X2_17_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_18_load_out_ap_vld = 1'b1;
    end else begin
        X2_18_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_19_load_out_ap_vld = 1'b1;
    end else begin
        X2_19_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_1_load_out_ap_vld = 1'b1;
    end else begin
        X2_1_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_20_load_out_ap_vld = 1'b1;
    end else begin
        X2_20_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_2_load_out_ap_vld = 1'b1;
    end else begin
        X2_2_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_3_load_out_ap_vld = 1'b1;
    end else begin
        X2_3_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_4_load_out_ap_vld = 1'b1;
    end else begin
        X2_4_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_5_load_out_ap_vld = 1'b1;
    end else begin
        X2_5_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_6_load_out_ap_vld = 1'b1;
    end else begin
        X2_6_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_7_load_out_ap_vld = 1'b1;
    end else begin
        X2_7_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_8_load_out_ap_vld = 1'b1;
    end else begin
        X2_8_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_9_load_out_ap_vld = 1'b1;
    end else begin
        X2_9_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (icmp_ln197_reg_997_pp0_iter3_reg == 1'd1))) begin
        X2_load_out_ap_vld = 1'b1;
    end else begin
        X2_load_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln197_fu_531_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k = 3'd0;
    end else begin
        ap_sig_allocacmp_k = k_2_fu_132;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign X2_10_load_out = X2_10_fu_176;

assign X2_11_load_out = X2_11_fu_180;

assign X2_12_load_out = X2_12_fu_184;

assign X2_13_load_out = X2_13_fu_188;

assign X2_14_load_out = X2_14_fu_192;

assign X2_15_load_out = X2_15_fu_196;

assign X2_16_load_out = X2_16_fu_200;

assign X2_17_load_out = X2_17_fu_204;

assign X2_18_load_out = X2_18_fu_208;

assign X2_19_load_out = X2_19_fu_212;

assign X2_1_load_out = X2_1_fu_140;

assign X2_20_load_out = X2_20_fu_216;

assign X2_2_load_out = X2_2_fu_144;

assign X2_3_load_out = X2_3_fu_148;

assign X2_4_load_out = X2_4_fu_152;

assign X2_5_load_out = X2_5_fu_156;

assign X2_6_load_out = X2_6_fu_160;

assign X2_7_load_out = X2_7_fu_164;

assign X2_8_load_out = X2_8_fu_168;

assign X2_9_load_out = X2_9_fu_172;

assign X2_load_out = X2_fu_136;

assign add_ln197_fu_537_p2 = (ap_sig_allocacmp_k + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_1043_p_ce = 1'b1;

assign grp_fu_1043_p_din0 = tmp_6_i_reg_1001;

assign grp_fu_1043_p_din1 = p_reload;

assign grp_fu_1043_p_opcode = 2'd1;

assign grp_fu_1048_p_ce = 1'b1;

assign grp_fu_1048_p_din0 = tmp_7_i_reg_1006;

assign grp_fu_1048_p_din1 = add_116_i_i_reload;

assign grp_fu_1048_p_opcode = 2'd1;

assign grp_fu_2613_p_ce = 1'b1;

assign grp_fu_2613_p_din0 = tmp_8_i_reg_1011;

assign grp_fu_2613_p_din1 = add_218_i_i_reload;

assign grp_fu_2613_p_opcode = 2'd1;

assign icmp_ln197_fu_531_p2 = ((ap_sig_allocacmp_k == 3'd7) ? 1'b1 : 1'b0);

assign tmp_6_i_fu_543_p15 = 'bx;

assign tmp_7_i_fu_579_p15 = 'bx;

assign tmp_8_i_fu_615_p15 = 'bx;

endmodule //ukf_accel_step_ukf_ut_process_3_2_Pipeline_VITIS_LOOP_197_7
