// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ukf_accel_step_ukf_accel_step,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.844000,HLS_SYN_LAT=956,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=30120,HLS_SYN_LUT=28610,HLS_VERSION=2024_2}" *)

module ukf_accel_step (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] z_q0;
wire   [31:0] q;
wire   [31:0] r;
wire   [31:0] x_in_q0;
wire   [31:0] S_in_q0;
reg   [31:0] x_in_load_reg_170;
wire    ap_CS_fsm_state2;
reg   [31:0] x_in_load_1_reg_180;
wire    ap_CS_fsm_state3;
reg   [31:0] x_in_load_2_reg_190;
wire    ap_CS_fsm_state4;
reg   [31:0] r_read_reg_195;
wire    ap_CS_fsm_state5;
reg   [31:0] q_read_reg_200;
wire   [31:0] empty_fu_153_p1;
reg   [31:0] empty_reg_205;
wire   [31:0] empty_56_fu_157_p1;
reg   [31:0] empty_56_reg_210;
wire   [31:0] empty_57_fu_161_p1;
reg   [31:0] empty_57_reg_215;
wire   [0:0] grp_ukf_step_3_2_s_fu_124_z_address0;
wire    grp_ukf_step_3_2_s_fu_124_z_ce0;
wire   [31:0] grp_ukf_step_3_2_s_fu_124_z_d0;
wire    grp_ukf_step_3_2_s_fu_124_z_we0;
wire   [3:0] grp_ukf_step_3_2_s_fu_124_S_in_address0;
wire    grp_ukf_step_3_2_s_fu_124_S_in_ce0;
wire   [31:0] grp_ukf_step_3_2_s_fu_124_S_in_d0;
wire    grp_ukf_step_3_2_s_fu_124_S_in_we0;
wire   [1:0] grp_ukf_step_3_2_s_fu_124_x_out_address0;
wire    grp_ukf_step_3_2_s_fu_124_x_out_ce0;
wire   [31:0] grp_ukf_step_3_2_s_fu_124_x_out_d0;
wire    grp_ukf_step_3_2_s_fu_124_x_out_we0;
wire   [3:0] grp_ukf_step_3_2_s_fu_124_S_out_address0;
wire    grp_ukf_step_3_2_s_fu_124_S_out_ce0;
wire   [31:0] grp_ukf_step_3_2_s_fu_124_S_out_d0;
wire    grp_ukf_step_3_2_s_fu_124_S_out_we0;
wire    grp_ukf_step_3_2_s_fu_124_ap_start;
wire    grp_ukf_step_3_2_s_fu_124_ap_done;
wire    grp_ukf_step_3_2_s_fu_124_ap_ready;
wire    grp_ukf_step_3_2_s_fu_124_ap_idle;
reg    grp_ukf_step_3_2_s_fu_124_ap_continue;
reg    grp_ukf_step_3_2_s_fu_124_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    ap_sync_reg_grp_ukf_step_3_2_s_fu_124_ap_ready;
reg    ap_sync_reg_grp_ukf_step_3_2_s_fu_124_ap_done;
reg    ap_block_state6_on_subcall_done;
wire    ap_sync_grp_ukf_step_3_2_s_fu_124_ap_ready;
reg    x_in_ce0_local;
reg   [1:0] x_in_address0_local;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_ukf_step_3_2_s_fu_124_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_ukf_step_3_2_s_fu_124_ap_ready = 1'b0;
#0 ap_sync_reg_grp_ukf_step_3_2_s_fu_124_ap_done = 1'b0;
end

ukf_accel_step_ukf_step_3_2_s grp_ukf_step_3_2_s_fu_124(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .z_address0(grp_ukf_step_3_2_s_fu_124_z_address0),
    .z_ce0(grp_ukf_step_3_2_s_fu_124_z_ce0),
    .z_d0(grp_ukf_step_3_2_s_fu_124_z_d0),
    .z_q0(z_q0),
    .z_we0(grp_ukf_step_3_2_s_fu_124_z_we0),
    .q(q_read_reg_200),
    .r(r_read_reg_195),
    .x_in_0_0_val(empty_reg_205),
    .x_in_0_1_val(empty_56_reg_210),
    .x_in_0_2_val(empty_57_reg_215),
    .S_in_address0(grp_ukf_step_3_2_s_fu_124_S_in_address0),
    .S_in_ce0(grp_ukf_step_3_2_s_fu_124_S_in_ce0),
    .S_in_d0(grp_ukf_step_3_2_s_fu_124_S_in_d0),
    .S_in_q0(S_in_q0),
    .S_in_we0(grp_ukf_step_3_2_s_fu_124_S_in_we0),
    .x_out_address0(grp_ukf_step_3_2_s_fu_124_x_out_address0),
    .x_out_ce0(grp_ukf_step_3_2_s_fu_124_x_out_ce0),
    .x_out_d0(grp_ukf_step_3_2_s_fu_124_x_out_d0),
    .x_out_q0(32'd0),
    .x_out_we0(grp_ukf_step_3_2_s_fu_124_x_out_we0),
    .S_out_address0(grp_ukf_step_3_2_s_fu_124_S_out_address0),
    .S_out_ce0(grp_ukf_step_3_2_s_fu_124_S_out_ce0),
    .S_out_d0(grp_ukf_step_3_2_s_fu_124_S_out_d0),
    .S_out_q0(32'd0),
    .S_out_we0(grp_ukf_step_3_2_s_fu_124_S_out_we0),
    .q_ap_vld(1'b1),
    .r_ap_vld(1'b1),
    .ap_start(grp_ukf_step_3_2_s_fu_124_ap_start),
    .x_in_0_0_val_ap_vld(1'b1),
    .x_in_0_1_val_ap_vld(1'b1),
    .x_in_0_2_val_ap_vld(1'b1),
    .ap_done(grp_ukf_step_3_2_s_fu_124_ap_done),
    .ap_ready(grp_ukf_step_3_2_s_fu_124_ap_ready),
    .ap_idle(grp_ukf_step_3_2_s_fu_124_ap_idle),
    .ap_continue(grp_ukf_step_3_2_s_fu_124_ap_continue)
);

ukf_accel_step_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .z_address0(grp_ukf_step_3_2_s_fu_124_z_address0),
    .z_ce0(grp_ukf_step_3_2_s_fu_124_z_ce0),
    .z_q0(z_q0),
    .q(q),
    .r(r),
    .x_in_address0(x_in_address0_local),
    .x_in_ce0(x_in_ce0_local),
    .x_in_q0(x_in_q0),
    .S_in_address0(grp_ukf_step_3_2_s_fu_124_S_in_address0),
    .S_in_ce0(grp_ukf_step_3_2_s_fu_124_S_in_ce0),
    .S_in_q0(S_in_q0),
    .x_out_address0(grp_ukf_step_3_2_s_fu_124_x_out_address0),
    .x_out_ce0(grp_ukf_step_3_2_s_fu_124_x_out_ce0),
    .x_out_we0(grp_ukf_step_3_2_s_fu_124_x_out_we0),
    .x_out_d0(grp_ukf_step_3_2_s_fu_124_x_out_d0),
    .S_out_address0(grp_ukf_step_3_2_s_fu_124_S_out_address0),
    .S_out_ce0(grp_ukf_step_3_2_s_fu_124_S_out_ce0),
    .S_out_we0(grp_ukf_step_3_2_s_fu_124_S_out_we0),
    .S_out_d0(grp_ukf_step_3_2_s_fu_124_S_out_d0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_ukf_step_3_2_s_fu_124_ap_done <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
            ap_sync_reg_grp_ukf_step_3_2_s_fu_124_ap_done <= 1'b0;
        end else if ((grp_ukf_step_3_2_s_fu_124_ap_done == 1'b1)) begin
            ap_sync_reg_grp_ukf_step_3_2_s_fu_124_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_ukf_step_3_2_s_fu_124_ap_ready <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
            ap_sync_reg_grp_ukf_step_3_2_s_fu_124_ap_ready <= 1'b0;
        end else if ((grp_ukf_step_3_2_s_fu_124_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_ukf_step_3_2_s_fu_124_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ukf_step_3_2_s_fu_124_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (ap_sync_grp_ukf_step_3_2_s_fu_124_ap_ready == 1'b0)))) begin
            grp_ukf_step_3_2_s_fu_124_ap_start_reg <= 1'b1;
        end else if ((grp_ukf_step_3_2_s_fu_124_ap_ready == 1'b1)) begin
            grp_ukf_step_3_2_s_fu_124_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        empty_56_reg_210 <= empty_56_fu_157_p1;
        empty_57_reg_215 <= empty_57_fu_161_p1;
        empty_reg_205 <= empty_fu_153_p1;
        q_read_reg_200 <= q;
        r_read_reg_195 <= r;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_in_load_1_reg_180 <= x_in_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        x_in_load_2_reg_190 <= x_in_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        x_in_load_reg_170 <= x_in_q0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state6_on_subcall_done)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
        grp_ukf_step_3_2_s_fu_124_ap_continue = 1'b1;
    end else begin
        grp_ukf_step_3_2_s_fu_124_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_in_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_in_address0_local = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        x_in_address0_local = 64'd0;
    end else begin
        x_in_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        x_in_ce0_local = 1'b1;
    end else begin
        x_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state6_on_subcall_done = ((ap_sync_reg_grp_ukf_step_3_2_s_fu_124_ap_ready & ap_sync_reg_grp_ukf_step_3_2_s_fu_124_ap_done) == 1'b0);
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_grp_ukf_step_3_2_s_fu_124_ap_ready = (grp_ukf_step_3_2_s_fu_124_ap_ready | ap_sync_reg_grp_ukf_step_3_2_s_fu_124_ap_ready);

assign empty_56_fu_157_p1 = x_in_load_1_reg_180;

assign empty_57_fu_161_p1 = x_in_load_2_reg_190;

assign empty_fu_153_p1 = x_in_load_reg_170;

assign grp_ukf_step_3_2_s_fu_124_ap_start = grp_ukf_step_3_2_s_fu_124_ap_start_reg;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "ukf_accel_step_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //ukf_accel_step

