// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ukf_accel_step_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        P12_1_load_2,
        P12_load_2,
        P12_1_load_1,
        P12_load_1,
        P12_1_load,
        P12_load,
        p_read,
        p_read3,
        p_read6,
        p_read9,
        p_read12,
        p_read15,
        p_read18,
        p_read21,
        p_read23,
        p_read25,
        p_read27,
        p_read29,
        p_read31,
        p_read33,
        p_read22,
        p_read24,
        p_read26,
        p_read28,
        p_read30,
        p_read32,
        p_read34,
        p_read1,
        p_read4,
        p_read7,
        p_read10,
        p_read13,
        p_read16,
        p_read19,
        p_read2,
        p_read5,
        p_read8,
        p_read11,
        p_read14,
        p_read17,
        p_read20,
        add_2_115_i_out,
        add_2_115_i_out_ap_vld,
        add_214_i_out,
        add_214_i_out_ap_vld,
        add_1_113_i_out,
        add_1_113_i_out_ap_vld,
        add_112_i_out,
        add_112_i_out_ap_vld,
        add_1911_i_out,
        add_1911_i_out_ap_vld,
        p_out,
        p_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] P12_1_load_2;
input  [31:0] P12_load_2;
input  [31:0] P12_1_load_1;
input  [31:0] P12_load_1;
input  [31:0] P12_1_load;
input  [31:0] P12_load;
input  [31:0] p_read;
input  [31:0] p_read3;
input  [31:0] p_read6;
input  [31:0] p_read9;
input  [31:0] p_read12;
input  [31:0] p_read15;
input  [31:0] p_read18;
input  [31:0] p_read21;
input  [31:0] p_read23;
input  [31:0] p_read25;
input  [31:0] p_read27;
input  [31:0] p_read29;
input  [31:0] p_read31;
input  [31:0] p_read33;
input  [31:0] p_read22;
input  [31:0] p_read24;
input  [31:0] p_read26;
input  [31:0] p_read28;
input  [31:0] p_read30;
input  [31:0] p_read32;
input  [31:0] p_read34;
input  [31:0] p_read1;
input  [31:0] p_read4;
input  [31:0] p_read7;
input  [31:0] p_read10;
input  [31:0] p_read13;
input  [31:0] p_read16;
input  [31:0] p_read19;
input  [31:0] p_read2;
input  [31:0] p_read5;
input  [31:0] p_read8;
input  [31:0] p_read11;
input  [31:0] p_read14;
input  [31:0] p_read17;
input  [31:0] p_read20;
output  [31:0] add_2_115_i_out;
output   add_2_115_i_out_ap_vld;
output  [31:0] add_214_i_out;
output   add_214_i_out_ap_vld;
output  [31:0] add_1_113_i_out;
output   add_1_113_i_out_ap_vld;
output  [31:0] add_112_i_out;
output   add_112_i_out_ap_vld;
output  [31:0] add_1911_i_out;
output   add_1911_i_out_ap_vld;
output  [31:0] p_out;
output   p_out_ap_vld;

reg ap_idle;
reg add_2_115_i_out_ap_vld;
reg add_214_i_out_ap_vld;
reg add_1_113_i_out_ap_vld;
reg add_112_i_out_ap_vld;
reg add_1911_i_out_ap_vld;
reg p_out_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln272_reg_863;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] w_Wc_address0;
wire   [31:0] w_Wc_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln272_fu_528_p2;
reg   [0:0] icmp_ln272_reg_863_pp0_iter1_reg;
reg   [0:0] icmp_ln272_reg_863_pp0_iter2_reg;
wire   [31:0] tmp_i_fu_545_p17;
reg   [31:0] tmp_i_reg_872;
wire   [31:0] tmp_i_58_fu_581_p17;
reg   [31:0] tmp_i_58_reg_877;
reg   [31:0] tmp_i_58_reg_877_pp0_iter1_reg;
wire   [31:0] tmp_21_i_fu_617_p17;
reg   [31:0] tmp_21_i_reg_884;
reg   [31:0] tmp_21_i_reg_884_pp0_iter1_reg;
wire   [31:0] tmp_22_i_fu_653_p17;
reg   [31:0] tmp_22_i_reg_891;
wire   [31:0] tmp_23_i_fu_689_p17;
reg   [31:0] tmp_23_i_reg_896;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [31:0] grp_fu_475_p2;
reg   [31:0] mul_i_reg_908;
wire   [31:0] grp_fu_480_p2;
reg   [31:0] mul_1_i_reg_914;
wire   [31:0] grp_fu_485_p2;
reg   [31:0] mul_2_i_reg_920;
reg   [31:0] mul7_i_reg_926;
reg   [31:0] mul34_i_reg_931;
reg   [31:0] mul34_1_i_reg_936;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [31:0] mul34_1_1_i_reg_951;
reg   [31:0] mul34_2_i_reg_956;
reg   [31:0] mul34_2_1_i_reg_961;
wire    ap_block_pp0_stage3_11001;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln272_fu_540_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] empty_fu_138;
wire   [31:0] grp_fu_467_p2;
reg   [31:0] ap_sig_allocacmp_p_load;
wire    ap_block_pp0_stage2;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter3_stage0;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [31:0] add_1911_i_fu_142;
wire   [31:0] grp_fu_471_p2;
reg   [31:0] ap_sig_allocacmp_add_1911_i_load;
reg   [31:0] add_112_i_fu_146;
reg   [31:0] ap_sig_allocacmp_add_112_i_load;
wire    ap_block_pp0_stage3;
reg   [31:0] add_1_113_i_fu_150;
reg   [31:0] ap_sig_allocacmp_add_1_113_i_load;
reg   [31:0] add_214_i_fu_154;
reg   [31:0] ap_sig_allocacmp_add_214_i_load;
reg   [31:0] add_2_115_i_fu_158;
reg   [31:0] ap_sig_allocacmp_add_2_115_i_load;
reg   [2:0] k_fu_162;
wire   [2:0] add_ln272_fu_534_p2;
reg   [2:0] ap_sig_allocacmp_k_7;
wire    ap_block_pp0_stage0_01001;
reg    w_Wc_ce0_local;
reg   [31:0] grp_fu_467_p0;
reg   [31:0] grp_fu_467_p1;
reg   [31:0] grp_fu_471_p0;
reg   [31:0] grp_fu_471_p1;
reg   [31:0] grp_fu_475_p0;
reg   [31:0] grp_fu_475_p1;
wire    ap_block_pp0_stage1;
reg   [31:0] grp_fu_480_p0;
reg   [31:0] grp_fu_480_p1;
reg   [31:0] grp_fu_485_p0;
reg   [31:0] grp_fu_485_p1;
wire   [31:0] tmp_i_fu_545_p15;
wire   [31:0] tmp_i_58_fu_581_p15;
wire   [31:0] tmp_21_i_fu_617_p15;
wire   [31:0] tmp_22_i_fu_653_p15;
wire   [31:0] tmp_23_i_fu_689_p15;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to4;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_i_fu_545_p1;
wire   [2:0] tmp_i_fu_545_p3;
wire   [2:0] tmp_i_fu_545_p5;
wire   [2:0] tmp_i_fu_545_p7;
wire  signed [2:0] tmp_i_fu_545_p9;
wire  signed [2:0] tmp_i_fu_545_p11;
wire  signed [2:0] tmp_i_fu_545_p13;
wire   [2:0] tmp_i_58_fu_581_p1;
wire   [2:0] tmp_i_58_fu_581_p3;
wire   [2:0] tmp_i_58_fu_581_p5;
wire   [2:0] tmp_i_58_fu_581_p7;
wire  signed [2:0] tmp_i_58_fu_581_p9;
wire  signed [2:0] tmp_i_58_fu_581_p11;
wire  signed [2:0] tmp_i_58_fu_581_p13;
wire   [2:0] tmp_21_i_fu_617_p1;
wire   [2:0] tmp_21_i_fu_617_p3;
wire   [2:0] tmp_21_i_fu_617_p5;
wire   [2:0] tmp_21_i_fu_617_p7;
wire  signed [2:0] tmp_21_i_fu_617_p9;
wire  signed [2:0] tmp_21_i_fu_617_p11;
wire  signed [2:0] tmp_21_i_fu_617_p13;
wire   [2:0] tmp_22_i_fu_653_p1;
wire   [2:0] tmp_22_i_fu_653_p3;
wire   [2:0] tmp_22_i_fu_653_p5;
wire   [2:0] tmp_22_i_fu_653_p7;
wire  signed [2:0] tmp_22_i_fu_653_p9;
wire  signed [2:0] tmp_22_i_fu_653_p11;
wire  signed [2:0] tmp_22_i_fu_653_p13;
wire   [2:0] tmp_23_i_fu_689_p1;
wire   [2:0] tmp_23_i_fu_689_p3;
wire   [2:0] tmp_23_i_fu_689_p5;
wire   [2:0] tmp_23_i_fu_689_p7;
wire  signed [2:0] tmp_23_i_fu_689_p9;
wire  signed [2:0] tmp_23_i_fu_689_p11;
wire  signed [2:0] tmp_23_i_fu_689_p13;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 empty_fu_138 = 32'd0;
#0 add_1911_i_fu_142 = 32'd0;
#0 add_112_i_fu_146 = 32'd0;
#0 add_1_113_i_fu_150 = 32'd0;
#0 add_214_i_fu_154 = 32'd0;
#0 add_2_115_i_fu_158 = 32'd0;
#0 k_fu_162 = 3'd0;
#0 ap_done_reg = 1'b0;
end

ukf_accel_step_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_w_Wc_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
w_Wc_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_Wc_address0),
    .ce0(w_Wc_ce0_local),
    .q0(w_Wc_q0)
);

ukf_accel_step_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U433(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_467_p0),
    .din1(grp_fu_467_p1),
    .ce(1'b1),
    .dout(grp_fu_467_p2)
);

ukf_accel_step_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U434(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_471_p0),
    .din1(grp_fu_471_p1),
    .ce(1'b1),
    .dout(grp_fu_471_p2)
);

ukf_accel_step_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U435(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_475_p0),
    .din1(grp_fu_475_p1),
    .ce(1'b1),
    .dout(grp_fu_475_p2)
);

ukf_accel_step_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U436(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_480_p0),
    .din1(grp_fu_480_p1),
    .ce(1'b1),
    .dout(grp_fu_480_p2)
);

ukf_accel_step_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U437(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_485_p0),
    .din1(grp_fu_485_p1),
    .ce(1'b1),
    .dout(grp_fu_485_p2)
);

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_15_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_15_3_32_1_1_U438(
    .din0(p_read),
    .din1(p_read3),
    .din2(p_read6),
    .din3(p_read9),
    .din4(p_read12),
    .din5(p_read15),
    .din6(p_read18),
    .def(tmp_i_fu_545_p15),
    .sel(ap_sig_allocacmp_k_7),
    .dout(tmp_i_fu_545_p17)
);

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_15_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_15_3_32_1_1_U439(
    .din0(p_read21),
    .din1(p_read23),
    .din2(p_read25),
    .din3(p_read27),
    .din4(p_read29),
    .din5(p_read31),
    .din6(p_read33),
    .def(tmp_i_58_fu_581_p15),
    .sel(ap_sig_allocacmp_k_7),
    .dout(tmp_i_58_fu_581_p17)
);

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_15_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_15_3_32_1_1_U440(
    .din0(p_read22),
    .din1(p_read24),
    .din2(p_read26),
    .din3(p_read28),
    .din4(p_read30),
    .din5(p_read32),
    .din6(p_read34),
    .def(tmp_21_i_fu_617_p15),
    .sel(ap_sig_allocacmp_k_7),
    .dout(tmp_21_i_fu_617_p17)
);

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_15_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_15_3_32_1_1_U441(
    .din0(p_read1),
    .din1(p_read4),
    .din2(p_read7),
    .din3(p_read10),
    .din4(p_read13),
    .din5(p_read16),
    .din6(p_read19),
    .def(tmp_22_i_fu_653_p15),
    .sel(ap_sig_allocacmp_k_7),
    .dout(tmp_22_i_fu_653_p17)
);

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_15_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_15_3_32_1_1_U442(
    .din0(p_read2),
    .din1(p_read5),
    .din2(p_read8),
    .din3(p_read11),
    .din4(p_read14),
    .din5(p_read17),
    .din6(p_read20),
    .def(tmp_23_i_fu_689_p15),
    .sel(ap_sig_allocacmp_k_7),
    .dout(tmp_23_i_fu_689_p17)
);

ukf_accel_step_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_112_i_fu_146 <= P12_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_112_i_fu_146 <= grp_fu_467_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_1911_i_fu_142 <= P12_1_load;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_1911_i_fu_142 <= grp_fu_471_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_1_113_i_fu_150 <= P12_1_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_1_113_i_fu_150 <= grp_fu_471_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add_214_i_fu_154 <= P12_load_2;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            add_214_i_fu_154 <= grp_fu_467_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add_2_115_i_fu_158 <= P12_1_load_2;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            add_2_115_i_fu_158 <= grp_fu_471_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_fu_138 <= P12_load;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        empty_fu_138 <= grp_fu_467_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln272_fu_528_p2 == 1'd0))) begin
            k_fu_162 <= add_ln272_fu_534_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_162 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln272_reg_863 <= icmp_ln272_fu_528_p2;
        icmp_ln272_reg_863_pp0_iter1_reg <= icmp_ln272_reg_863;
        icmp_ln272_reg_863_pp0_iter2_reg <= icmp_ln272_reg_863_pp0_iter1_reg;
        tmp_21_i_reg_884 <= tmp_21_i_fu_617_p17;
        tmp_21_i_reg_884_pp0_iter1_reg <= tmp_21_i_reg_884;
        tmp_22_i_reg_891 <= tmp_22_i_fu_653_p17;
        tmp_23_i_reg_896 <= tmp_23_i_fu_689_p17;
        tmp_i_58_reg_877 <= tmp_i_58_fu_581_p17;
        tmp_i_58_reg_877_pp0_iter1_reg <= tmp_i_58_reg_877;
        tmp_i_reg_872 <= tmp_i_fu_545_p17;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul34_1_1_i_reg_951 <= grp_fu_475_p2;
        mul34_2_1_i_reg_961 <= grp_fu_485_p2;
        mul34_2_i_reg_956 <= grp_fu_480_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul34_1_i_reg_936 <= grp_fu_485_p2;
        mul34_i_reg_931 <= grp_fu_480_p2;
        mul7_i_reg_926 <= grp_fu_475_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_1_i_reg_914 <= grp_fu_480_p2;
        mul_2_i_reg_920 <= grp_fu_485_p2;
        mul_i_reg_908 <= grp_fu_475_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln272_reg_863_pp0_iter2_reg == 1'd1))) begin
        add_112_i_out_ap_vld = 1'b1;
    end else begin
        add_112_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln272_reg_863_pp0_iter2_reg == 1'd1))) begin
        add_1911_i_out_ap_vld = 1'b1;
    end else begin
        add_1911_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln272_reg_863_pp0_iter2_reg == 1'd1))) begin
        add_1_113_i_out_ap_vld = 1'b1;
    end else begin
        add_1_113_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln272_reg_863_pp0_iter2_reg == 1'd1))) begin
        add_214_i_out_ap_vld = 1'b1;
    end else begin
        add_214_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln272_reg_863_pp0_iter2_reg == 1'd1))) begin
        add_2_115_i_out_ap_vld = 1'b1;
    end else begin
        add_2_115_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln272_reg_863 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln272_reg_863_pp0_iter2_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_add_112_i_load = grp_fu_467_p2;
    end else begin
        ap_sig_allocacmp_add_112_i_load = add_112_i_fu_146;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_add_1911_i_load = grp_fu_471_p2;
    end else begin
        ap_sig_allocacmp_add_1911_i_load = add_1911_i_fu_142;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_add_1_113_i_load = grp_fu_471_p2;
    end else begin
        ap_sig_allocacmp_add_1_113_i_load = add_1_113_i_fu_150;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add_214_i_load = grp_fu_467_p2;
    end else begin
        ap_sig_allocacmp_add_214_i_load = add_214_i_fu_154;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_add_2_115_i_load = grp_fu_471_p2;
    end else begin
        ap_sig_allocacmp_add_2_115_i_load = add_2_115_i_fu_158;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_7 = 3'd0;
    end else begin
        ap_sig_allocacmp_k_7 = k_fu_162;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_p_load = grp_fu_467_p2;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_138;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_467_p0 = ap_sig_allocacmp_add_214_i_load;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_467_p0 = ap_sig_allocacmp_add_112_i_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_467_p0 = ap_sig_allocacmp_p_load;
    end else begin
        grp_fu_467_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_467_p1 = mul34_2_i_reg_956;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_467_p1 = mul34_1_i_reg_936;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_467_p1 = mul7_i_reg_926;
    end else begin
        grp_fu_467_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_471_p0 = ap_sig_allocacmp_add_2_115_i_load;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_471_p0 = ap_sig_allocacmp_add_1_113_i_load;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_471_p0 = ap_sig_allocacmp_add_1911_i_load;
    end else begin
        grp_fu_471_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_471_p1 = mul34_2_1_i_reg_961;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_471_p1 = mul34_1_1_i_reg_951;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_471_p1 = mul34_i_reg_931;
    end else begin
        grp_fu_471_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_475_p0 = mul_1_i_reg_914;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_475_p0 = mul_i_reg_908;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_475_p0 = w_Wc_q0;
    end else begin
        grp_fu_475_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_475_p1 = tmp_21_i_reg_884_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_475_p1 = tmp_i_58_reg_877_pp0_iter1_reg;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_475_p1 = tmp_i_reg_872;
    end else begin
        grp_fu_475_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_480_p0 = mul_2_i_reg_920;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_480_p0 = mul_i_reg_908;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_480_p0 = w_Wc_q0;
    end else begin
        grp_fu_480_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_480_p1 = tmp_i_58_reg_877_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_480_p1 = tmp_21_i_reg_884_pp0_iter1_reg;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_480_p1 = tmp_22_i_reg_891;
    end else begin
        grp_fu_480_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_485_p0 = mul_2_i_reg_920;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_485_p0 = mul_1_i_reg_914;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_485_p0 = w_Wc_q0;
    end else begin
        grp_fu_485_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_485_p1 = tmp_21_i_reg_884_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_485_p1 = tmp_i_58_reg_877_pp0_iter1_reg;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_485_p1 = tmp_23_i_reg_896;
    end else begin
        grp_fu_485_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln272_reg_863_pp0_iter2_reg == 1'd1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_Wc_ce0_local = 1'b1;
    end else begin
        w_Wc_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_112_i_out = add_112_i_fu_146;

assign add_1911_i_out = add_1911_i_fu_142;

assign add_1_113_i_out = add_1_113_i_fu_150;

assign add_214_i_out = add_214_i_fu_154;

assign add_2_115_i_out = add_2_115_i_fu_158;

assign add_ln272_fu_534_p2 = (ap_sig_allocacmp_k_7 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign ap_ready = ap_ready_sig;

assign icmp_ln272_fu_528_p2 = ((ap_sig_allocacmp_k_7 == 3'd7) ? 1'b1 : 1'b0);

assign p_out = empty_fu_138;

assign tmp_21_i_fu_617_p15 = 'bx;

assign tmp_22_i_fu_653_p15 = 'bx;

assign tmp_23_i_fu_689_p15 = 'bx;

assign tmp_i_58_fu_581_p15 = 'bx;

assign tmp_i_fu_545_p15 = 'bx;

assign w_Wc_address0 = zext_ln272_fu_540_p1;

assign zext_ln272_fu_540_p1 = ap_sig_allocacmp_k_7;

endmodule //ukf_accel_step_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3
