// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ukf_accel_step_ukf_ut_meas_3_2_Pipeline_VITIS_LOOP_256_15 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_reload144,
        P_0_i_address0,
        P_0_i_ce0,
        P_0_i_we0,
        P_0_i_d0,
        P_0_i_address1,
        P_0_i_ce1,
        P_0_i_q1,
        P_1_i_address0,
        P_1_i_ce0,
        P_1_i_we0,
        P_1_i_d0,
        P_1_i_address1,
        P_1_i_ce1,
        P_1_i_q1,
        mul1_i,
        p_out,
        p_out_ap_vld,
        grp_fu_631_p_din0,
        grp_fu_631_p_din1,
        grp_fu_631_p_opcode,
        grp_fu_631_p_dout0,
        grp_fu_631_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_reload144;
output  [0:0] P_0_i_address0;
output   P_0_i_ce0;
output   P_0_i_we0;
output  [31:0] P_0_i_d0;
output  [0:0] P_0_i_address1;
output   P_0_i_ce1;
input  [31:0] P_0_i_q1;
output  [0:0] P_1_i_address0;
output   P_1_i_ce0;
output   P_1_i_we0;
output  [31:0] P_1_i_d0;
output  [0:0] P_1_i_address1;
output   P_1_i_ce1;
input  [31:0] P_1_i_q1;
input  [31:0] mul1_i;
output  [31:0] p_out;
output   p_out_ap_vld;
output  [31:0] grp_fu_631_p_din0;
output  [31:0] grp_fu_631_p_din1;
output  [0:0] grp_fu_631_p_opcode;
input  [31:0] grp_fu_631_p_dout0;
output   grp_fu_631_p_ce;

reg ap_idle;
reg p_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln256_fu_127_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln256_reg_205;
reg   [0:0] icmp_ln256_reg_205_pp0_iter1_reg;
reg   [0:0] icmp_ln256_reg_205_pp0_iter2_reg;
reg   [0:0] icmp_ln256_reg_205_pp0_iter3_reg;
reg   [0:0] icmp_ln256_reg_205_pp0_iter4_reg;
reg   [0:0] icmp_ln256_reg_205_pp0_iter5_reg;
reg   [0:0] P_1_i_addr_reg_214;
reg   [0:0] P_1_i_addr_reg_214_pp0_iter1_reg;
reg   [0:0] P_1_i_addr_reg_214_pp0_iter2_reg;
reg   [0:0] P_1_i_addr_reg_214_pp0_iter3_reg;
reg   [0:0] P_1_i_addr_reg_214_pp0_iter4_reg;
reg   [0:0] P_1_i_addr_reg_214_pp0_iter5_reg;
reg   [0:0] P_1_i_addr_reg_214_pp0_iter6_reg;
wire   [0:0] icmp_ln256_1_fu_145_p2;
reg   [0:0] icmp_ln256_1_reg_220;
wire   [0:0] icmp_ln256_2_fu_151_p2;
reg   [0:0] icmp_ln256_2_reg_225;
reg   [0:0] icmp_ln256_2_reg_225_pp0_iter1_reg;
reg   [0:0] icmp_ln256_2_reg_225_pp0_iter2_reg;
reg   [0:0] icmp_ln256_2_reg_225_pp0_iter3_reg;
reg   [0:0] icmp_ln256_2_reg_225_pp0_iter4_reg;
reg   [0:0] icmp_ln256_2_reg_225_pp0_iter5_reg;
reg   [0:0] icmp_ln256_2_reg_225_pp0_iter6_reg;
wire   [31:0] select_ln256_fu_162_p3;
reg   [31:0] select_ln256_reg_229;
wire   [31:0] bitcast_ln256_fu_169_p1;
reg   [31:0] add2_i_reg_239;
wire   [63:0] zext_ln256_fu_139_p1;
wire    ap_block_pp0_stage0;
reg   [1:0] i_fu_40;
wire   [1:0] add_ln256_fu_133_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_i_3;
reg   [31:0] empty_fu_44;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
wire    ap_block_pp0_stage0_01001;
reg    P_0_i_ce1_local;
reg    P_0_i_we0_local;
wire   [31:0] bitcast_ln256_1_fu_173_p1;
reg    P_0_i_ce0_local;
reg    P_1_i_ce1_local;
reg    P_1_i_we0_local;
reg    P_1_i_ce0_local;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 i_fu_40 = 2'd0;
#0 empty_fu_44 = 32'd0;
#0 ap_done_reg = 1'b0;
end

ukf_accel_step_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_fu_44 <= p_reload144;
        end else if (((ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln256_2_reg_225_pp0_iter6_reg == 1'd1))) begin
            empty_fu_44 <= add2_i_reg_239;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln256_fu_127_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_40 <= add_ln256_fu_133_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_40 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        P_1_i_addr_reg_214 <= zext_ln256_fu_139_p1;
        P_1_i_addr_reg_214_pp0_iter1_reg <= P_1_i_addr_reg_214;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln256_1_reg_220 <= icmp_ln256_1_fu_145_p2;
        icmp_ln256_2_reg_225 <= icmp_ln256_2_fu_151_p2;
        icmp_ln256_2_reg_225_pp0_iter1_reg <= icmp_ln256_2_reg_225;
        icmp_ln256_reg_205 <= icmp_ln256_fu_127_p2;
        icmp_ln256_reg_205_pp0_iter1_reg <= icmp_ln256_reg_205;
        select_ln256_reg_229 <= select_ln256_fu_162_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        P_1_i_addr_reg_214_pp0_iter2_reg <= P_1_i_addr_reg_214_pp0_iter1_reg;
        P_1_i_addr_reg_214_pp0_iter3_reg <= P_1_i_addr_reg_214_pp0_iter2_reg;
        P_1_i_addr_reg_214_pp0_iter4_reg <= P_1_i_addr_reg_214_pp0_iter3_reg;
        P_1_i_addr_reg_214_pp0_iter5_reg <= P_1_i_addr_reg_214_pp0_iter4_reg;
        P_1_i_addr_reg_214_pp0_iter6_reg <= P_1_i_addr_reg_214_pp0_iter5_reg;
        add2_i_reg_239 <= grp_fu_631_p_dout0;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        icmp_ln256_2_reg_225_pp0_iter2_reg <= icmp_ln256_2_reg_225_pp0_iter1_reg;
        icmp_ln256_2_reg_225_pp0_iter3_reg <= icmp_ln256_2_reg_225_pp0_iter2_reg;
        icmp_ln256_2_reg_225_pp0_iter4_reg <= icmp_ln256_2_reg_225_pp0_iter3_reg;
        icmp_ln256_2_reg_225_pp0_iter5_reg <= icmp_ln256_2_reg_225_pp0_iter4_reg;
        icmp_ln256_2_reg_225_pp0_iter6_reg <= icmp_ln256_2_reg_225_pp0_iter5_reg;
        icmp_ln256_reg_205_pp0_iter2_reg <= icmp_ln256_reg_205_pp0_iter1_reg;
        icmp_ln256_reg_205_pp0_iter3_reg <= icmp_ln256_reg_205_pp0_iter2_reg;
        icmp_ln256_reg_205_pp0_iter4_reg <= icmp_ln256_reg_205_pp0_iter3_reg;
        icmp_ln256_reg_205_pp0_iter5_reg <= icmp_ln256_reg_205_pp0_iter4_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        P_0_i_ce0_local = 1'b1;
    end else begin
        P_0_i_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        P_0_i_ce1_local = 1'b1;
    end else begin
        P_0_i_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln256_2_reg_225_pp0_iter6_reg == 1'd1))) begin
        P_0_i_we0_local = 1'b1;
    end else begin
        P_0_i_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        P_1_i_ce0_local = 1'b1;
    end else begin
        P_1_i_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        P_1_i_ce1_local = 1'b1;
    end else begin
        P_1_i_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln256_2_reg_225_pp0_iter6_reg == 1'd0))) begin
        P_1_i_we0_local = 1'b1;
    end else begin
        P_1_i_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln256_fu_127_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_3 = 2'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_40;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (icmp_ln256_reg_205_pp0_iter5_reg == 1'd1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign P_0_i_address0 = 64'd0;

assign P_0_i_address1 = zext_ln256_fu_139_p1;

assign P_0_i_ce0 = P_0_i_ce0_local;

assign P_0_i_ce1 = P_0_i_ce1_local;

assign P_0_i_d0 = bitcast_ln256_1_fu_173_p1;

assign P_0_i_we0 = P_0_i_we0_local;

assign P_1_i_address0 = P_1_i_addr_reg_214_pp0_iter6_reg;

assign P_1_i_address1 = zext_ln256_fu_139_p1;

assign P_1_i_ce0 = P_1_i_ce0_local;

assign P_1_i_ce1 = P_1_i_ce1_local;

assign P_1_i_d0 = bitcast_ln256_1_fu_173_p1;

assign P_1_i_we0 = P_1_i_we0_local;

assign add_ln256_fu_133_p2 = (ap_sig_allocacmp_i_3 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln256_1_fu_173_p1 = add2_i_reg_239;

assign bitcast_ln256_fu_169_p1 = select_ln256_reg_229;

assign grp_fu_631_p_ce = 1'b1;

assign grp_fu_631_p_din0 = bitcast_ln256_fu_169_p1;

assign grp_fu_631_p_din1 = mul1_i;

assign grp_fu_631_p_opcode = 2'd0;

assign icmp_ln256_1_fu_145_p2 = ((ap_sig_allocacmp_i_3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln256_2_fu_151_p2 = ((ap_sig_allocacmp_i_3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln256_fu_127_p2 = ((ap_sig_allocacmp_i_3 == 2'd2) ? 1'b1 : 1'b0);

assign p_out = empty_fu_44;

assign select_ln256_fu_162_p3 = ((icmp_ln256_1_reg_220[0:0] == 1'b1) ? P_1_i_q1 : P_0_i_q1);

assign zext_ln256_fu_139_p1 = ap_sig_allocacmp_i_3;

endmodule //ukf_accel_step_ukf_ut_meas_3_2_Pipeline_VITIS_LOOP_256_15
