// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ukf_accel_step_ukf_ut_process_3_2_Pipeline_VITIS_LOOP_216_13_VITIS_LOOP_217_14 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        S1_address0,
        S1_ce0,
        S1_we0,
        S1_d0,
        Lmat_address0,
        Lmat_ce0,
        Lmat_q0,
        Lmat_3_address0,
        Lmat_3_ce0,
        Lmat_3_q0,
        Lmat_4_address0,
        Lmat_4_ce0,
        Lmat_4_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] S1_address0;
output   S1_ce0;
output   S1_we0;
output  [31:0] S1_d0;
output  [1:0] Lmat_address0;
output   Lmat_ce0;
input  [31:0] Lmat_q0;
output  [1:0] Lmat_3_address0;
output   Lmat_3_ce0;
input  [31:0] Lmat_3_q0;
output  [1:0] Lmat_4_address0;
output   Lmat_4_ce0;
input  [31:0] Lmat_4_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln216_fu_130_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] icmp_ln217_fu_145_p2;
reg   [0:0] icmp_ln217_reg_280;
wire    ap_block_pp0_stage0_11001;
wire   [1:0] select_ln216_fu_151_p3;
reg   [1:0] select_ln216_reg_285;
wire   [63:0] zext_ln217_fu_159_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln217_3_fu_225_p1;
reg   [1:0] c_fu_48;
wire   [1:0] add_ln217_fu_166_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_c_load;
reg   [1:0] r_fu_52;
wire   [1:0] select_ln216_1_fu_191_p3;
reg   [3:0] indvar_flatten6_fu_56;
wire   [3:0] add_ln216_1_fu_136_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    Lmat_ce0_local;
reg    Lmat_3_ce0_local;
reg    Lmat_4_ce0_local;
reg    S1_we0_local;
wire   [31:0] tmp_14_i_fu_230_p9;
reg    S1_ce0_local;
wire   [1:0] add_ln216_fu_185_p2;
wire   [3:0] p_shl_fu_202_p3;
wire   [3:0] zext_ln217_1_fu_198_p1;
wire   [3:0] sub_ln217_fu_210_p2;
wire   [3:0] zext_ln217_2_fu_216_p1;
wire   [3:0] add_ln217_1_fu_219_p2;
wire   [31:0] tmp_14_i_fu_230_p7;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_14_i_fu_230_p1;
wire   [1:0] tmp_14_i_fu_230_p3;
wire  signed [1:0] tmp_14_i_fu_230_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 c_fu_48 = 2'd0;
#0 r_fu_52 = 2'd0;
#0 indvar_flatten6_fu_56 = 4'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U238(
    .din0(Lmat_q0),
    .din1(Lmat_3_q0),
    .din2(Lmat_4_q0),
    .def(tmp_14_i_fu_230_p7),
    .sel(select_ln216_1_fu_191_p3),
    .dout(tmp_14_i_fu_230_p9)
);

ukf_accel_step_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln216_fu_130_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_48 <= add_ln217_fu_166_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_48 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln216_fu_130_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_56 <= add_ln216_1_fu_136_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_56 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            r_fu_52 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            r_fu_52 <= select_ln216_1_fu_191_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln217_reg_280 <= icmp_ln217_fu_145_p2;
        select_ln216_reg_285 <= select_ln216_fu_151_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Lmat_3_ce0_local = 1'b1;
    end else begin
        Lmat_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Lmat_4_ce0_local = 1'b1;
    end else begin
        Lmat_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Lmat_ce0_local = 1'b1;
    end else begin
        Lmat_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S1_ce0_local = 1'b1;
    end else begin
        S1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S1_we0_local = 1'b1;
    end else begin
        S1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln216_fu_130_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 2'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_56;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Lmat_3_address0 = zext_ln217_fu_159_p1;

assign Lmat_3_ce0 = Lmat_3_ce0_local;

assign Lmat_4_address0 = zext_ln217_fu_159_p1;

assign Lmat_4_ce0 = Lmat_4_ce0_local;

assign Lmat_address0 = zext_ln217_fu_159_p1;

assign Lmat_ce0 = Lmat_ce0_local;

assign S1_address0 = zext_ln217_3_fu_225_p1;

assign S1_ce0 = S1_ce0_local;

assign S1_d0 = tmp_14_i_fu_230_p9;

assign S1_we0 = S1_we0_local;

assign add_ln216_1_fu_136_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 4'd1);

assign add_ln216_fu_185_p2 = (r_fu_52 + 2'd1);

assign add_ln217_1_fu_219_p2 = (sub_ln217_fu_210_p2 + zext_ln217_2_fu_216_p1);

assign add_ln217_fu_166_p2 = (select_ln216_fu_151_p3 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln216_fu_130_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln217_fu_145_p2 = ((ap_sig_allocacmp_c_load == 2'd3) ? 1'b1 : 1'b0);

assign p_shl_fu_202_p3 = {{select_ln216_1_fu_191_p3}, {2'd0}};

assign select_ln216_1_fu_191_p3 = ((icmp_ln217_reg_280[0:0] == 1'b1) ? add_ln216_fu_185_p2 : r_fu_52);

assign select_ln216_fu_151_p3 = ((icmp_ln217_fu_145_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_c_load);

assign sub_ln217_fu_210_p2 = (p_shl_fu_202_p3 - zext_ln217_1_fu_198_p1);

assign tmp_14_i_fu_230_p7 = 'bx;

assign zext_ln217_1_fu_198_p1 = select_ln216_1_fu_191_p3;

assign zext_ln217_2_fu_216_p1 = select_ln216_reg_285;

assign zext_ln217_3_fu_225_p1 = add_ln217_1_fu_219_p2;

assign zext_ln217_fu_159_p1 = select_ln216_fu_151_p3;

endmodule //ukf_accel_step_ukf_ut_process_3_2_Pipeline_VITIS_LOOP_216_13_VITIS_LOOP_217_14
