// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ukf_accel_step_cross_cov_3_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        P12_address0,
        P12_ce0,
        P12_we0,
        P12_d0,
        P12_q0,
        P12_address1,
        P12_ce1,
        P12_we1,
        P12_d1,
        P12_q1,
        P12_1_address0,
        P12_1_ce0,
        P12_1_we0,
        P12_1_d0,
        P12_1_q0,
        P12_1_address1,
        P12_1_ce1,
        P12_1_we1,
        P12_1_d1,
        P12_1_q1
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
input  [31:0] p_read5;
input  [31:0] p_read6;
input  [31:0] p_read7;
input  [31:0] p_read8;
input  [31:0] p_read9;
input  [31:0] p_read10;
input  [31:0] p_read11;
input  [31:0] p_read12;
input  [31:0] p_read13;
input  [31:0] p_read14;
input  [31:0] p_read15;
input  [31:0] p_read16;
input  [31:0] p_read17;
input  [31:0] p_read18;
input  [31:0] p_read19;
input  [31:0] p_read20;
input  [31:0] p_read21;
input  [31:0] p_read22;
input  [31:0] p_read23;
input  [31:0] p_read24;
input  [31:0] p_read25;
input  [31:0] p_read26;
input  [31:0] p_read27;
input  [31:0] p_read28;
input  [31:0] p_read29;
input  [31:0] p_read30;
input  [31:0] p_read31;
input  [31:0] p_read32;
input  [31:0] p_read33;
input  [31:0] p_read34;
output  [1:0] P12_address0;
output   P12_ce0;
output   P12_we0;
output  [31:0] P12_d0;
input  [31:0] P12_q0;
output  [1:0] P12_address1;
output   P12_ce1;
output   P12_we1;
output  [31:0] P12_d1;
input  [31:0] P12_q1;
output  [1:0] P12_1_address0;
output   P12_1_ce0;
output   P12_1_we0;
output  [31:0] P12_1_d0;
input  [31:0] P12_1_q0;
output  [1:0] P12_1_address1;
output   P12_1_ce1;
output   P12_1_we1;
output  [31:0] P12_1_d1;
input  [31:0] P12_1_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[1:0] P12_address0;
reg P12_ce0;
reg P12_we0;
reg[31:0] P12_d0;
reg[1:0] P12_1_address0;
reg P12_1_ce0;
reg P12_1_we0;
reg[31:0] P12_1_d0;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] P12_addr_reg_554;
wire    ap_CS_fsm_state3;
wire   [1:0] P12_1_addr_reg_559;
wire   [1:0] P12_addr_1_reg_564;
wire    ap_CS_fsm_state4;
wire   [1:0] P12_1_addr_1_reg_569;
reg   [31:0] P12_load_reg_586;
reg   [31:0] P12_1_load_reg_591;
reg   [31:0] p_read_83_reg_596;
wire    ap_CS_fsm_state5;
reg   [31:0] p_read_84_reg_601;
reg   [31:0] p_read_85_reg_606;
reg   [31:0] p_read_86_reg_611;
reg   [31:0] p_read3065_reg_616;
reg   [31:0] p_read_87_reg_621;
reg   [31:0] p_read_88_reg_626;
reg   [31:0] p_read_89_reg_631;
reg   [31:0] p_read_90_reg_636;
reg   [31:0] p_read_91_reg_641;
reg   [31:0] p_read_92_reg_646;
reg   [31:0] p_read_93_reg_651;
reg   [31:0] p_read_94_reg_656;
reg   [31:0] p_read_95_reg_661;
reg   [31:0] p_read2055_reg_666;
reg   [31:0] p_read_96_reg_671;
reg   [31:0] p_read_97_reg_676;
reg   [31:0] p_read_98_reg_681;
reg   [31:0] p_read_99_reg_686;
reg   [31:0] p_read_100_reg_691;
reg   [31:0] p_read_101_reg_696;
reg   [31:0] p_read_102_reg_701;
reg   [31:0] p_read_103_reg_706;
reg   [31:0] p_read_104_reg_711;
reg   [31:0] p_read1045_reg_716;
reg   [31:0] p_read944_reg_721;
reg   [31:0] p_read843_reg_726;
reg   [31:0] p_read742_reg_731;
reg   [31:0] p_read641_reg_736;
reg   [31:0] p_read540_reg_741;
reg   [31:0] p_read439_reg_746;
reg   [31:0] p_read338_reg_751;
reg   [31:0] p_read237_reg_756;
reg   [31:0] p_read136_reg_761;
reg   [31:0] p_read35_reg_766;
reg   [31:0] P12_load_1_reg_771;
reg   [31:0] P12_1_load_1_reg_776;
reg   [31:0] P12_load_2_reg_781;
reg   [31:0] P12_1_load_2_reg_786;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_start;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_done;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_idle;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_ready;
wire   [1:0] grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_address0;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_ce0;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_we0;
wire   [31:0] grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_d0;
wire   [1:0] grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_1_address0;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_1_ce0;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_1_we0;
wire   [31:0] grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_1_d0;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_start;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_done;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_idle;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_ready;
wire   [31:0] grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_2_115_i_out;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_2_115_i_out_ap_vld;
wire   [31:0] grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_214_i_out;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_214_i_out_ap_vld;
wire   [31:0] grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_1_113_i_out;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_1_113_i_out_ap_vld;
wire   [31:0] grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_112_i_out;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_112_i_out_ap_vld;
wire   [31:0] grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_1911_i_out;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_1911_i_out_ap_vld;
wire   [31:0] grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_p_out;
wire    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_p_out_ap_vld;
reg    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_start_reg;
reg    ap_block_state1_ignore_call41;
wire    ap_CS_fsm_state2;
wire    P12_we0_out;
wire    P12_1_we0_out;
reg    grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    P12_ce0_local;
reg   [1:0] P12_address0_local;
reg    P12_ce1_local;
reg   [1:0] P12_address1_local;
reg    P12_we0_local;
reg    P12_we1_local;
reg   [31:0] P12_d1_local;
reg    P12_1_ce0_local;
reg   [1:0] P12_1_address0_local;
reg    P12_1_ce1_local;
reg   [1:0] P12_1_address1_local;
reg    P12_1_we0_local;
reg    P12_1_we1_local;
reg   [31:0] P12_1_d1_local;
reg   [7:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_start_reg = 1'b0;
#0 grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_start_reg = 1'b0;
end

ukf_accel_step_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2 grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_start),
    .ap_done(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_done),
    .ap_idle(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_idle),
    .ap_ready(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_ready),
    .P12_address0(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_address0),
    .P12_ce0(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_ce0),
    .P12_we0(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_we0),
    .P12_d0(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_d0),
    .P12_1_address0(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_1_address0),
    .P12_1_ce0(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_1_ce0),
    .P12_1_we0(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_1_we0),
    .P12_1_d0(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_1_d0)
);

ukf_accel_step_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3 grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_start),
    .ap_done(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_done),
    .ap_idle(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_idle),
    .ap_ready(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_ready),
    .P12_1_load_2(P12_1_load_2_reg_786),
    .P12_load_2(P12_load_2_reg_781),
    .P12_1_load_1(P12_1_load_1_reg_776),
    .P12_load_1(P12_load_1_reg_771),
    .P12_1_load(P12_1_load_reg_591),
    .P12_load(P12_load_reg_586),
    .p_read(p_read35_reg_766),
    .p_read3(p_read338_reg_751),
    .p_read6(p_read641_reg_736),
    .p_read9(p_read944_reg_721),
    .p_read12(p_read_103_reg_706),
    .p_read15(p_read_100_reg_691),
    .p_read18(p_read_97_reg_676),
    .p_read21(p_read_95_reg_661),
    .p_read23(p_read_93_reg_651),
    .p_read25(p_read_91_reg_641),
    .p_read27(p_read_89_reg_631),
    .p_read29(p_read_87_reg_621),
    .p_read31(p_read_86_reg_611),
    .p_read33(p_read_84_reg_601),
    .p_read22(p_read_94_reg_656),
    .p_read24(p_read_92_reg_646),
    .p_read26(p_read_90_reg_636),
    .p_read28(p_read_88_reg_626),
    .p_read30(p_read3065_reg_616),
    .p_read32(p_read_85_reg_606),
    .p_read34(p_read_83_reg_596),
    .p_read1(p_read136_reg_761),
    .p_read4(p_read439_reg_746),
    .p_read7(p_read742_reg_731),
    .p_read10(p_read1045_reg_716),
    .p_read13(p_read_102_reg_701),
    .p_read16(p_read_99_reg_686),
    .p_read19(p_read_96_reg_671),
    .p_read2(p_read237_reg_756),
    .p_read5(p_read540_reg_741),
    .p_read8(p_read843_reg_726),
    .p_read11(p_read_104_reg_711),
    .p_read14(p_read_101_reg_696),
    .p_read17(p_read_98_reg_681),
    .p_read20(p_read2055_reg_666),
    .add_2_115_i_out(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_2_115_i_out),
    .add_2_115_i_out_ap_vld(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_2_115_i_out_ap_vld),
    .add_214_i_out(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_214_i_out),
    .add_214_i_out_ap_vld(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_214_i_out_ap_vld),
    .add_1_113_i_out(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_1_113_i_out),
    .add_1_113_i_out_ap_vld(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_1_113_i_out_ap_vld),
    .add_112_i_out(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_112_i_out),
    .add_112_i_out_ap_vld(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_112_i_out_ap_vld),
    .add_1911_i_out(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_1911_i_out),
    .add_1911_i_out_ap_vld(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_1911_i_out_ap_vld),
    .p_out(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_p_out),
    .p_out_ap_vld(grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_p_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call41) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_start_reg <= 1'b1;
        end else if ((grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_ready == 1'b1)) begin
            grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_start_reg <= 1'b1;
        end else if ((grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_ready == 1'b1)) begin
            grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        P12_1_load_1_reg_776 <= P12_1_q1;
        P12_1_load_2_reg_786 <= P12_1_q0;
        P12_load_1_reg_771 <= P12_q1;
        P12_load_2_reg_781 <= P12_q0;
        p_read1045_reg_716 <= p_read10;
        p_read136_reg_761 <= p_read1;
        p_read2055_reg_666 <= p_read20;
        p_read237_reg_756 <= p_read2;
        p_read3065_reg_616 <= p_read30;
        p_read338_reg_751 <= p_read3;
        p_read35_reg_766 <= p_read;
        p_read439_reg_746 <= p_read4;
        p_read540_reg_741 <= p_read5;
        p_read641_reg_736 <= p_read6;
        p_read742_reg_731 <= p_read7;
        p_read843_reg_726 <= p_read8;
        p_read944_reg_721 <= p_read9;
        p_read_100_reg_691 <= p_read15;
        p_read_101_reg_696 <= p_read14;
        p_read_102_reg_701 <= p_read13;
        p_read_103_reg_706 <= p_read12;
        p_read_104_reg_711 <= p_read11;
        p_read_83_reg_596 <= p_read34;
        p_read_84_reg_601 <= p_read33;
        p_read_85_reg_606 <= p_read32;
        p_read_86_reg_611 <= p_read31;
        p_read_87_reg_621 <= p_read29;
        p_read_88_reg_626 <= p_read28;
        p_read_89_reg_631 <= p_read27;
        p_read_90_reg_636 <= p_read26;
        p_read_91_reg_641 <= p_read25;
        p_read_92_reg_646 <= p_read24;
        p_read_93_reg_651 <= p_read23;
        p_read_94_reg_656 <= p_read22;
        p_read_95_reg_661 <= p_read21;
        p_read_96_reg_671 <= p_read19;
        p_read_97_reg_676 <= p_read18;
        p_read_98_reg_681 <= p_read17;
        p_read_99_reg_686 <= p_read16;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        P12_1_load_reg_591 <= P12_1_q0;
        P12_load_reg_586 <= P12_q0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        P12_1_address0 = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_1_address0;
    end else begin
        P12_1_address0 = P12_1_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        P12_1_address0_local = P12_1_addr_reg_559;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        P12_1_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        P12_1_address0_local = 64'd0;
    end else begin
        P12_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        P12_1_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        P12_1_address1_local = P12_1_addr_1_reg_569;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        P12_1_address1_local = 64'd1;
    end else begin
        P12_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        P12_1_ce0 = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_1_ce0;
    end else begin
        P12_1_ce0 = P12_1_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4))) begin
        P12_1_ce0_local = 1'b1;
    end else begin
        P12_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4))) begin
        P12_1_ce1_local = 1'b1;
    end else begin
        P12_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        P12_1_d0 = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_1_d0;
    end else begin
        P12_1_d0 = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_1911_i_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        P12_1_d1_local = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_2_115_i_out;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        P12_1_d1_local = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_1_113_i_out;
    end else begin
        P12_1_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        P12_1_we0 = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_1_we0;
    end else begin
        P12_1_we0 = (1'b0 | P12_1_we0_out);
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        P12_1_we0_local = 1'b1;
    end else begin
        P12_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        P12_1_we1_local = 1'b1;
    end else begin
        P12_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        P12_address0 = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_address0;
    end else begin
        P12_address0 = P12_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        P12_address0_local = P12_addr_reg_554;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        P12_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        P12_address0_local = 64'd0;
    end else begin
        P12_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        P12_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        P12_address1_local = P12_addr_1_reg_564;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        P12_address1_local = 64'd1;
    end else begin
        P12_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        P12_ce0 = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_ce0;
    end else begin
        P12_ce0 = P12_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4))) begin
        P12_ce0_local = 1'b1;
    end else begin
        P12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4))) begin
        P12_ce1_local = 1'b1;
    end else begin
        P12_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        P12_d0 = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_d0;
    end else begin
        P12_d0 = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_p_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        P12_d1_local = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_214_i_out;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        P12_d1_local = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_add_112_i_out;
    end else begin
        P12_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        P12_we0 = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_P12_we0;
    end else begin
        P12_we0 = (1'b0 | P12_we0_out);
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        P12_we0_local = 1'b1;
    end else begin
        P12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        P12_we1_local = 1'b1;
    end else begin
        P12_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign P12_1_addr_1_reg_569 = 64'd1;

assign P12_1_addr_reg_559 = 64'd0;

assign P12_1_address1 = P12_1_address1_local;

assign P12_1_ce1 = P12_1_ce1_local;

assign P12_1_d1 = P12_1_d1_local;

assign P12_1_we0_out = P12_1_we0_local;

assign P12_1_we1 = P12_1_we1_local;

assign P12_addr_1_reg_564 = 64'd1;

assign P12_addr_reg_554 = 64'd0;

assign P12_address1 = P12_address1_local;

assign P12_ce1 = P12_ce1_local;

assign P12_d1 = P12_d1_local;

assign P12_we0_out = P12_we0_local;

assign P12_we1 = P12_we1_local;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call41 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_start = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_267_1_VITIS_LOOP_268_2_fu_394_ap_start_reg;

assign grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_start = grp_cross_cov_3_2_Pipeline_VITIS_LOOP_272_3_fu_402_ap_start_reg;

endmodule //ukf_accel_step_cross_cov_3_2_s
