// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ukf_accel_step_ukf_ut_process_3_2_Pipeline_VITIS_LOOP_193_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x1_load_2,
        x1_load_1,
        x1_load,
        mux_case_01_i_i_reload,
        mux_case_15_i_i_reload,
        mux_case_28_i_i_reload,
        mux_case_311_i_i_reload,
        mux_case_414_i_i_reload,
        mux_case_517_i_i_reload,
        mux_case_622_i_i_reload,
        mux_case_01525_i_i_reload,
        mux_case_11628_i_i_reload,
        mux_case_21731_i_i_reload,
        mux_case_31834_i_i_reload,
        mux_case_41937_i_i_reload,
        mux_case_52040_i_i_reload,
        mux_case_62143_i_i_reload,
        mux_case_02246_i_i_reload,
        mux_case_12349_i_i_reload,
        mux_case_22452_i_i_reload,
        mux_case_32555_i_i_reload,
        mux_case_42658_i_i_reload,
        mux_case_52761_i_i_reload,
        mux_case_62864_i_i_reload,
        add_218_i_i_out,
        add_218_i_i_out_ap_vld,
        add_116_i_i_out,
        add_116_i_i_out_ap_vld,
        p_out,
        p_out_ap_vld,
        grp_fu_1043_p_din0,
        grp_fu_1043_p_din1,
        grp_fu_1043_p_opcode,
        grp_fu_1043_p_dout0,
        grp_fu_1043_p_ce,
        grp_fu_1058_p_din0,
        grp_fu_1058_p_din1,
        grp_fu_1058_p_dout0,
        grp_fu_1058_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] x1_load_2;
input  [31:0] x1_load_1;
input  [31:0] x1_load;
input  [31:0] mux_case_01_i_i_reload;
input  [31:0] mux_case_15_i_i_reload;
input  [31:0] mux_case_28_i_i_reload;
input  [31:0] mux_case_311_i_i_reload;
input  [31:0] mux_case_414_i_i_reload;
input  [31:0] mux_case_517_i_i_reload;
input  [31:0] mux_case_622_i_i_reload;
input  [31:0] mux_case_01525_i_i_reload;
input  [31:0] mux_case_11628_i_i_reload;
input  [31:0] mux_case_21731_i_i_reload;
input  [31:0] mux_case_31834_i_i_reload;
input  [31:0] mux_case_41937_i_i_reload;
input  [31:0] mux_case_52040_i_i_reload;
input  [31:0] mux_case_62143_i_i_reload;
input  [31:0] mux_case_02246_i_i_reload;
input  [31:0] mux_case_12349_i_i_reload;
input  [31:0] mux_case_22452_i_i_reload;
input  [31:0] mux_case_32555_i_i_reload;
input  [31:0] mux_case_42658_i_i_reload;
input  [31:0] mux_case_52761_i_i_reload;
input  [31:0] mux_case_62864_i_i_reload;
output  [31:0] add_218_i_i_out;
output   add_218_i_i_out_ap_vld;
output  [31:0] add_116_i_i_out;
output   add_116_i_i_out_ap_vld;
output  [31:0] p_out;
output   p_out_ap_vld;
output  [31:0] grp_fu_1043_p_din0;
output  [31:0] grp_fu_1043_p_din1;
output  [0:0] grp_fu_1043_p_opcode;
input  [31:0] grp_fu_1043_p_dout0;
output   grp_fu_1043_p_ce;
output  [31:0] grp_fu_1058_p_din0;
output  [31:0] grp_fu_1058_p_din1;
input  [31:0] grp_fu_1058_p_dout0;
output   grp_fu_1058_p_ce;

reg ap_idle;
reg add_218_i_i_out_ap_vld;
reg add_116_i_i_out_ap_vld;
reg p_out_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln193_reg_524;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] w_Wm2_address0;
wire   [31:0] w_Wm2_q0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln193_fu_324_p2;
reg   [0:0] icmp_ln193_reg_524_pp0_iter1_reg;
wire   [31:0] tmp_3_i_fu_341_p17;
reg   [31:0] tmp_3_i_reg_533;
wire   [31:0] tmp_4_i_fu_377_p17;
reg   [31:0] tmp_4_i_reg_538;
wire   [31:0] tmp_5_i_fu_413_p17;
reg   [31:0] tmp_5_i_reg_543;
reg   [31:0] w_Wm2_load_reg_548;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] mul_i_i_reg_553;
reg   [31:0] mul_1_i_i_reg_563;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [31:0] mul_2_i_i_reg_573;
wire    ap_block_pp0_stage3_11001;
wire   [63:0] zext_ln193_fu_336_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] empty_fu_98;
reg   [31:0] ap_sig_allocacmp_p_load;
wire    ap_block_pp0_stage1;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
wire    ap_block_pp0_stage3;
reg   [31:0] add_116_i_i_fu_102;
reg   [31:0] ap_sig_allocacmp_add_116_i_i_load;
wire    ap_block_pp0_stage2;
reg   [31:0] add_218_i_i_fu_106;
reg   [31:0] ap_sig_allocacmp_add_218_i_i_load;
reg   [2:0] k_1_fu_110;
wire   [2:0] add_ln193_fu_330_p2;
reg   [2:0] ap_sig_allocacmp_k;
wire    ap_block_pp0_stage3_01001;
reg    w_Wm2_ce0_local;
reg   [31:0] grp_fu_292_p0;
reg   [31:0] grp_fu_292_p1;
reg   [31:0] grp_fu_296_p0;
reg   [31:0] grp_fu_296_p1;
wire   [31:0] tmp_3_i_fu_341_p15;
wire   [31:0] tmp_4_i_fu_377_p15;
wire   [31:0] tmp_5_i_fu_413_p15;
wire    ap_block_pp0_stage1_00001;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage3_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_3_i_fu_341_p1;
wire   [2:0] tmp_3_i_fu_341_p3;
wire   [2:0] tmp_3_i_fu_341_p5;
wire   [2:0] tmp_3_i_fu_341_p7;
wire  signed [2:0] tmp_3_i_fu_341_p9;
wire  signed [2:0] tmp_3_i_fu_341_p11;
wire  signed [2:0] tmp_3_i_fu_341_p13;
wire   [2:0] tmp_4_i_fu_377_p1;
wire   [2:0] tmp_4_i_fu_377_p3;
wire   [2:0] tmp_4_i_fu_377_p5;
wire   [2:0] tmp_4_i_fu_377_p7;
wire  signed [2:0] tmp_4_i_fu_377_p9;
wire  signed [2:0] tmp_4_i_fu_377_p11;
wire  signed [2:0] tmp_4_i_fu_377_p13;
wire   [2:0] tmp_5_i_fu_413_p1;
wire   [2:0] tmp_5_i_fu_413_p3;
wire   [2:0] tmp_5_i_fu_413_p5;
wire   [2:0] tmp_5_i_fu_413_p7;
wire  signed [2:0] tmp_5_i_fu_413_p9;
wire  signed [2:0] tmp_5_i_fu_413_p11;
wire  signed [2:0] tmp_5_i_fu_413_p13;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 empty_fu_98 = 32'd0;
#0 add_116_i_i_fu_102 = 32'd0;
#0 add_218_i_i_fu_106 = 32'd0;
#0 k_1_fu_110 = 3'd0;
#0 ap_done_reg = 1'b0;
end

ukf_accel_step_ukf_ut_process_3_2_Pipeline_VITIS_LOOP_193_5_w_Wm2_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 7 ),
    .AddressWidth( 3 ))
w_Wm2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_Wm2_address0),
    .ce0(w_Wm2_ce0_local),
    .q0(w_Wm2_q0)
);

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_15_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_15_3_32_1_1_U67(
    .din0(mux_case_01_i_i_reload),
    .din1(mux_case_15_i_i_reload),
    .din2(mux_case_28_i_i_reload),
    .din3(mux_case_311_i_i_reload),
    .din4(mux_case_414_i_i_reload),
    .din5(mux_case_517_i_i_reload),
    .din6(mux_case_622_i_i_reload),
    .def(tmp_3_i_fu_341_p15),
    .sel(ap_sig_allocacmp_k),
    .dout(tmp_3_i_fu_341_p17)
);

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_15_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_15_3_32_1_1_U68(
    .din0(mux_case_01525_i_i_reload),
    .din1(mux_case_11628_i_i_reload),
    .din2(mux_case_21731_i_i_reload),
    .din3(mux_case_31834_i_i_reload),
    .din4(mux_case_41937_i_i_reload),
    .din5(mux_case_52040_i_i_reload),
    .din6(mux_case_62143_i_i_reload),
    .def(tmp_4_i_fu_377_p15),
    .sel(ap_sig_allocacmp_k),
    .dout(tmp_4_i_fu_377_p17)
);

(* dissolve_hierarchy = "yes" *) ukf_accel_step_sparsemux_15_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_15_3_32_1_1_U69(
    .din0(mux_case_02246_i_i_reload),
    .din1(mux_case_12349_i_i_reload),
    .din2(mux_case_22452_i_i_reload),
    .din3(mux_case_32555_i_i_reload),
    .din4(mux_case_42658_i_i_reload),
    .din5(mux_case_52761_i_i_reload),
    .din6(mux_case_62864_i_i_reload),
    .def(tmp_5_i_fu_413_p15),
    .sel(ap_sig_allocacmp_k),
    .dout(tmp_5_i_fu_413_p17)
);

ukf_accel_step_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        add_116_i_i_fu_102 <= x1_load_1;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_116_i_i_fu_102 <= grp_fu_1043_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        add_218_i_i_fu_106 <= x1_load_2;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_218_i_i_fu_106 <= grp_fu_1043_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        empty_fu_98 <= x1_load;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_fu_98 <= grp_fu_1043_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln193_fu_324_p2 == 1'd0))) begin
            k_1_fu_110 <= add_ln193_fu_330_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_1_fu_110 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln193_reg_524 <= icmp_ln193_fu_324_p2;
        icmp_ln193_reg_524_pp0_iter1_reg <= icmp_ln193_reg_524;
        tmp_3_i_reg_533 <= tmp_3_i_fu_341_p17;
        tmp_4_i_reg_538 <= tmp_4_i_fu_377_p17;
        tmp_5_i_reg_543 <= tmp_5_i_fu_413_p17;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_1_i_i_reg_563 <= grp_fu_1058_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul_2_i_i_reg_573 <= grp_fu_1058_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_i_i_reg_553 <= grp_fu_1058_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        w_Wm2_load_reg_548 <= w_Wm2_q0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln193_reg_524_pp0_iter1_reg == 1'd1))) begin
        add_116_i_i_out_ap_vld = 1'b1;
    end else begin
        add_116_i_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln193_reg_524_pp0_iter1_reg == 1'd1))) begin
        add_218_i_i_out_ap_vld = 1'b1;
    end else begin
        add_218_i_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln193_reg_524 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_sig_allocacmp_add_116_i_i_load = grp_fu_1043_p_dout0;
    end else begin
        ap_sig_allocacmp_add_116_i_i_load = add_116_i_i_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_add_218_i_i_load = grp_fu_1043_p_dout0;
    end else begin
        ap_sig_allocacmp_add_218_i_i_load = add_218_i_i_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k = 3'd0;
    end else begin
        ap_sig_allocacmp_k = k_1_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_p_load = grp_fu_1043_p_dout0;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_98;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_292_p0 = ap_sig_allocacmp_add_218_i_i_load;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_292_p0 = ap_sig_allocacmp_add_116_i_i_load;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_292_p0 = ap_sig_allocacmp_p_load;
        end else begin
            grp_fu_292_p0 = 'bx;
        end
    end else begin
        grp_fu_292_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_292_p1 = mul_2_i_i_reg_573;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_292_p1 = mul_1_i_i_reg_563;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_292_p1 = mul_i_i_reg_553;
        end else begin
            grp_fu_292_p1 = 'bx;
        end
    end else begin
        grp_fu_292_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_296_p0 = w_Wm2_load_reg_548;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_296_p0 = w_Wm2_q0;
    end else begin
        grp_fu_296_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_296_p1 = tmp_5_i_reg_543;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_296_p1 = tmp_4_i_reg_538;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_296_p1 = tmp_3_i_reg_533;
        end else begin
            grp_fu_296_p1 = 'bx;
        end
    end else begin
        grp_fu_296_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln193_reg_524_pp0_iter1_reg == 1'd1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_Wm2_ce0_local = 1'b1;
    end else begin
        w_Wm2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_116_i_i_out = add_116_i_i_fu_102;

assign add_218_i_i_out = add_218_i_i_fu_106;

assign add_ln193_fu_330_p2 = (ap_sig_allocacmp_k + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign ap_ready = ap_ready_sig;

assign grp_fu_1043_p_ce = 1'b1;

assign grp_fu_1043_p_din0 = grp_fu_292_p0;

assign grp_fu_1043_p_din1 = grp_fu_292_p1;

assign grp_fu_1043_p_opcode = 2'd0;

assign grp_fu_1058_p_ce = 1'b1;

assign grp_fu_1058_p_din0 = grp_fu_296_p0;

assign grp_fu_1058_p_din1 = grp_fu_296_p1;

assign icmp_ln193_fu_324_p2 = ((ap_sig_allocacmp_k == 3'd7) ? 1'b1 : 1'b0);

assign p_out = empty_fu_98;

assign tmp_3_i_fu_341_p15 = 'bx;

assign tmp_4_i_fu_377_p15 = 'bx;

assign tmp_5_i_fu_413_p15 = 'bx;

assign w_Wm2_address0 = zext_ln193_fu_336_p1;

assign zext_ln193_fu_336_p1 = ap_sig_allocacmp_k;

endmodule //ukf_accel_step_ukf_ut_process_3_2_Pipeline_VITIS_LOOP_193_5
