// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ukf_accel_step_ukf_update_3_2_2_Pipeline_VITIS_LOOP_315_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        S2_0_address0,
        S2_0_ce0,
        S2_0_q0,
        S2_1_address0,
        S2_1_ce0,
        S2_1_q0,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        grp_fu_397_p_din0,
        grp_fu_397_p_din1,
        grp_fu_397_p_dout0,
        grp_fu_397_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] S2_0_address0;
output   S2_0_ce0;
input  [31:0] S2_0_q0;
output  [0:0] S2_1_address0;
output   S2_1_ce0;
input  [31:0] S2_1_q0;
output  [31:0] p_out;
output   p_out_ap_vld;
output  [31:0] p_out1;
output   p_out1_ap_vld;
output  [31:0] grp_fu_397_p_din0;
output  [31:0] grp_fu_397_p_din1;
input  [31:0] grp_fu_397_p_dout0;
output   grp_fu_397_p_ce;

reg ap_idle;
reg p_out_ap_vld;
reg p_out1_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln315_fu_103_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [1:0] j_1_reg_201;
reg   [0:0] icmp_ln315_reg_207;
reg   [0:0] icmp_ln315_reg_207_pp0_iter1_reg;
reg   [0:0] icmp_ln315_reg_207_pp0_iter2_reg;
reg   [0:0] icmp_ln315_reg_207_pp0_iter3_reg;
reg   [0:0] icmp_ln315_reg_207_pp0_iter4_reg;
reg   [0:0] icmp_ln315_reg_207_pp0_iter5_reg;
reg   [0:0] icmp_ln315_reg_207_pp0_iter6_reg;
reg   [0:0] icmp_ln315_reg_207_pp0_iter7_reg;
reg   [0:0] icmp_ln315_reg_207_pp0_iter8_reg;
reg   [0:0] icmp_ln315_reg_207_pp0_iter9_reg;
reg   [0:0] icmp_ln315_reg_207_pp0_iter10_reg;
reg   [0:0] icmp_ln315_reg_207_pp0_iter11_reg;
reg   [0:0] icmp_ln315_reg_207_pp0_iter12_reg;
wire   [31:0] select_ln315_2_fu_131_p3;
reg   [31:0] select_ln315_2_reg_221;
wire   [0:0] icmp_ln315_1_fu_139_p2;
reg   [0:0] icmp_ln315_1_reg_226;
reg   [0:0] icmp_ln315_1_reg_226_pp0_iter2_reg;
reg   [0:0] icmp_ln315_1_reg_226_pp0_iter3_reg;
reg   [0:0] icmp_ln315_1_reg_226_pp0_iter4_reg;
reg   [0:0] icmp_ln315_1_reg_226_pp0_iter5_reg;
reg   [0:0] icmp_ln315_1_reg_226_pp0_iter6_reg;
reg   [0:0] icmp_ln315_1_reg_226_pp0_iter7_reg;
reg   [0:0] icmp_ln315_1_reg_226_pp0_iter8_reg;
reg   [0:0] icmp_ln315_1_reg_226_pp0_iter9_reg;
reg   [0:0] icmp_ln315_1_reg_226_pp0_iter10_reg;
reg   [0:0] icmp_ln315_1_reg_226_pp0_iter11_reg;
reg   [0:0] icmp_ln315_1_reg_226_pp0_iter12_reg;
reg   [0:0] icmp_ln315_1_reg_226_pp0_iter13_reg;
reg   [31:0] div_reg_232;
wire   [63:0] zext_ln315_fu_115_p1;
wire    ap_block_pp0_stage0;
reg   [1:0] j_fu_38;
wire   [1:0] add_ln315_fu_109_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_j_1;
reg   [31:0] empty_fu_42;
wire   [31:0] select_ln315_1_fu_156_p3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg   [31:0] empty_54_fu_46;
wire   [31:0] select_ln315_fu_150_p3;
wire    ap_block_pp0_stage0_01001;
reg    S2_0_ce0_local;
reg    S2_1_ce0_local;
wire   [0:0] icmp_ln315_2_fu_126_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 j_fu_38 = 2'd0;
#0 empty_fu_42 = 32'd0;
#0 empty_54_fu_46 = 32'd0;
#0 ap_done_reg = 1'b0;
end

ukf_accel_step_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln315_fu_103_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_38 <= add_ln315_fu_109_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_38 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        div_reg_232 <= grp_fu_397_p_dout0;
        icmp_ln315_1_reg_226_pp0_iter10_reg <= icmp_ln315_1_reg_226_pp0_iter9_reg;
        icmp_ln315_1_reg_226_pp0_iter11_reg <= icmp_ln315_1_reg_226_pp0_iter10_reg;
        icmp_ln315_1_reg_226_pp0_iter12_reg <= icmp_ln315_1_reg_226_pp0_iter11_reg;
        icmp_ln315_1_reg_226_pp0_iter13_reg <= icmp_ln315_1_reg_226_pp0_iter12_reg;
        icmp_ln315_1_reg_226_pp0_iter2_reg <= icmp_ln315_1_reg_226;
        icmp_ln315_1_reg_226_pp0_iter3_reg <= icmp_ln315_1_reg_226_pp0_iter2_reg;
        icmp_ln315_1_reg_226_pp0_iter4_reg <= icmp_ln315_1_reg_226_pp0_iter3_reg;
        icmp_ln315_1_reg_226_pp0_iter5_reg <= icmp_ln315_1_reg_226_pp0_iter4_reg;
        icmp_ln315_1_reg_226_pp0_iter6_reg <= icmp_ln315_1_reg_226_pp0_iter5_reg;
        icmp_ln315_1_reg_226_pp0_iter7_reg <= icmp_ln315_1_reg_226_pp0_iter6_reg;
        icmp_ln315_1_reg_226_pp0_iter8_reg <= icmp_ln315_1_reg_226_pp0_iter7_reg;
        icmp_ln315_1_reg_226_pp0_iter9_reg <= icmp_ln315_1_reg_226_pp0_iter8_reg;
        icmp_ln315_reg_207_pp0_iter10_reg <= icmp_ln315_reg_207_pp0_iter9_reg;
        icmp_ln315_reg_207_pp0_iter11_reg <= icmp_ln315_reg_207_pp0_iter10_reg;
        icmp_ln315_reg_207_pp0_iter12_reg <= icmp_ln315_reg_207_pp0_iter11_reg;
        icmp_ln315_reg_207_pp0_iter2_reg <= icmp_ln315_reg_207_pp0_iter1_reg;
        icmp_ln315_reg_207_pp0_iter3_reg <= icmp_ln315_reg_207_pp0_iter2_reg;
        icmp_ln315_reg_207_pp0_iter4_reg <= icmp_ln315_reg_207_pp0_iter3_reg;
        icmp_ln315_reg_207_pp0_iter5_reg <= icmp_ln315_reg_207_pp0_iter4_reg;
        icmp_ln315_reg_207_pp0_iter6_reg <= icmp_ln315_reg_207_pp0_iter5_reg;
        icmp_ln315_reg_207_pp0_iter7_reg <= icmp_ln315_reg_207_pp0_iter6_reg;
        icmp_ln315_reg_207_pp0_iter8_reg <= icmp_ln315_reg_207_pp0_iter7_reg;
        icmp_ln315_reg_207_pp0_iter9_reg <= icmp_ln315_reg_207_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln315_1_reg_226 <= icmp_ln315_1_fu_139_p2;
        icmp_ln315_reg_207 <= icmp_ln315_fu_103_p2;
        icmp_ln315_reg_207_pp0_iter1_reg <= icmp_ln315_reg_207;
        j_1_reg_201 <= ap_sig_allocacmp_j_1;
        select_ln315_2_reg_221 <= select_ln315_2_fu_131_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        empty_54_fu_46 <= select_ln315_fu_150_p3;
        empty_fu_42 <= select_ln315_1_fu_156_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S2_0_ce0_local = 1'b1;
    end else begin
        S2_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S2_1_ce0_local = 1'b1;
    end else begin
        S2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln315_fu_103_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_38;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (icmp_ln315_reg_207_pp0_iter12_reg == 1'd1))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (icmp_ln315_reg_207_pp0_iter12_reg == 1'd1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign S2_0_address0 = zext_ln315_fu_115_p1;

assign S2_0_ce0 = S2_0_ce0_local;

assign S2_1_address0 = zext_ln315_fu_115_p1;

assign S2_1_ce0 = S2_1_ce0_local;

assign add_ln315_fu_109_p2 = (ap_sig_allocacmp_j_1 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_397_p_ce = 1'b1;

assign grp_fu_397_p_din0 = 32'd1065353216;

assign grp_fu_397_p_din1 = select_ln315_2_reg_221;

assign icmp_ln315_1_fu_139_p2 = ((j_1_reg_201 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln315_2_fu_126_p2 = ((j_1_reg_201 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln315_fu_103_p2 = ((ap_sig_allocacmp_j_1 == 2'd2) ? 1'b1 : 1'b0);

assign p_out = empty_54_fu_46;

assign p_out1 = empty_fu_42;

assign select_ln315_1_fu_156_p3 = ((icmp_ln315_1_reg_226_pp0_iter13_reg[0:0] == 1'b1) ? div_reg_232 : empty_fu_42);

assign select_ln315_2_fu_131_p3 = ((icmp_ln315_2_fu_126_p2[0:0] == 1'b1) ? S2_1_q0 : S2_0_q0);

assign select_ln315_fu_150_p3 = ((icmp_ln315_1_reg_226_pp0_iter13_reg[0:0] == 1'b1) ? empty_54_fu_46 : div_reg_232);

assign zext_ln315_fu_115_p1 = ap_sig_allocacmp_j_1;

endmodule //ukf_accel_step_ukf_update_3_2_2_Pipeline_VITIS_LOOP_315_1
