// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ukf_accel_step_ukf_update_3_2_2_Pipeline_VITIS_LOOP_295_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        k_8_cast,
        mul_ln296,
        R_address0,
        R_ce0,
        R_we0,
        R_d0,
        R_address1,
        R_ce1,
        R_q1,
        x_address0,
        x_ce0,
        x_we0,
        x_d0,
        x_address1,
        x_ce1,
        x_q1,
        mul3425_i,
        div22_i,
        mul3425_i_in,
        grp_fu_383_p_din0,
        grp_fu_383_p_din1,
        grp_fu_383_p_opcode,
        grp_fu_383_p_dout0,
        grp_fu_383_p_ce,
        grp_fu_906_p_din0,
        grp_fu_906_p_din1,
        grp_fu_906_p_opcode,
        grp_fu_906_p_dout0,
        grp_fu_906_p_ce,
        grp_fu_387_p_din0,
        grp_fu_387_p_din1,
        grp_fu_387_p_dout0,
        grp_fu_387_p_ce,
        grp_fu_393_p_din0,
        grp_fu_393_p_din1,
        grp_fu_393_p_dout0,
        grp_fu_393_p_ce,
        grp_fu_914_p_din0,
        grp_fu_914_p_din1,
        grp_fu_914_p_dout0,
        grp_fu_914_p_ce,
        grp_fu_397_p_din0,
        grp_fu_397_p_din1,
        grp_fu_397_p_dout0,
        grp_fu_397_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [1:0] k_8_cast;
input  [2:0] mul_ln296;
output  [3:0] R_address0;
output   R_ce0;
output   R_we0;
output  [31:0] R_d0;
output  [3:0] R_address1;
output   R_ce1;
input  [31:0] R_q1;
output  [1:0] x_address0;
output   x_ce0;
output   x_we0;
output  [31:0] x_d0;
output  [1:0] x_address1;
output   x_ce1;
input  [31:0] x_q1;
input  [31:0] mul3425_i;
input  [31:0] div22_i;
input  [31:0] mul3425_i_in;
output  [31:0] grp_fu_383_p_din0;
output  [31:0] grp_fu_383_p_din1;
output  [0:0] grp_fu_383_p_opcode;
input  [31:0] grp_fu_383_p_dout0;
output   grp_fu_383_p_ce;
output  [31:0] grp_fu_906_p_din0;
output  [31:0] grp_fu_906_p_din1;
output  [0:0] grp_fu_906_p_opcode;
input  [31:0] grp_fu_906_p_dout0;
output   grp_fu_906_p_ce;
output  [31:0] grp_fu_387_p_din0;
output  [31:0] grp_fu_387_p_din1;
input  [31:0] grp_fu_387_p_dout0;
output   grp_fu_387_p_ce;
output  [31:0] grp_fu_393_p_din0;
output  [31:0] grp_fu_393_p_din1;
input  [31:0] grp_fu_393_p_dout0;
output   grp_fu_393_p_ce;
output  [31:0] grp_fu_914_p_din0;
output  [31:0] grp_fu_914_p_din1;
input  [31:0] grp_fu_914_p_dout0;
output   grp_fu_914_p_ce;
output  [31:0] grp_fu_397_p_din0;
output  [31:0] grp_fu_397_p_din1;
input  [31:0] grp_fu_397_p_dout0;
output   grp_fu_397_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln295_fu_157_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] R_addr_reg_221;
reg   [3:0] R_addr_reg_221_pp0_iter1_reg;
reg   [3:0] R_addr_reg_221_pp0_iter2_reg;
reg   [3:0] R_addr_reg_221_pp0_iter3_reg;
reg   [3:0] R_addr_reg_221_pp0_iter4_reg;
reg   [3:0] R_addr_reg_221_pp0_iter5_reg;
reg   [3:0] R_addr_reg_221_pp0_iter6_reg;
reg   [3:0] R_addr_reg_221_pp0_iter7_reg;
reg   [3:0] R_addr_reg_221_pp0_iter8_reg;
reg   [3:0] R_addr_reg_221_pp0_iter9_reg;
reg   [3:0] R_addr_reg_221_pp0_iter10_reg;
reg   [3:0] R_addr_reg_221_pp0_iter11_reg;
reg   [3:0] R_addr_reg_221_pp0_iter12_reg;
reg   [3:0] R_addr_reg_221_pp0_iter13_reg;
reg   [3:0] R_addr_reg_221_pp0_iter14_reg;
reg   [3:0] R_addr_reg_221_pp0_iter15_reg;
reg   [3:0] R_addr_reg_221_pp0_iter16_reg;
reg   [3:0] R_addr_reg_221_pp0_iter17_reg;
reg   [3:0] R_addr_reg_221_pp0_iter18_reg;
reg   [3:0] R_addr_reg_221_pp0_iter19_reg;
reg   [3:0] R_addr_reg_221_pp0_iter20_reg;
reg   [3:0] R_addr_reg_221_pp0_iter21_reg;
reg   [1:0] x_addr_reg_227;
reg   [1:0] x_addr_reg_227_pp0_iter1_reg;
reg   [1:0] x_addr_reg_227_pp0_iter2_reg;
reg   [1:0] x_addr_reg_227_pp0_iter3_reg;
reg   [1:0] x_addr_reg_227_pp0_iter4_reg;
reg   [1:0] x_addr_reg_227_pp0_iter5_reg;
reg   [1:0] x_addr_reg_227_pp0_iter6_reg;
reg   [1:0] x_addr_reg_227_pp0_iter7_reg;
reg   [1:0] x_addr_reg_227_pp0_iter8_reg;
reg   [1:0] x_addr_reg_227_pp0_iter9_reg;
reg   [31:0] rkj_reg_233;
reg   [31:0] rkj_reg_233_pp0_iter2_reg;
reg   [31:0] rkj_reg_233_pp0_iter3_reg;
reg   [31:0] rkj_reg_233_pp0_iter4_reg;
reg   [31:0] mul37_i_reg_245;
reg   [31:0] mul42_i_reg_250;
reg   [31:0] mul43_i_reg_255;
reg   [31:0] add38_i_reg_260;
reg   [31:0] sub_i_reg_265;
reg   [31:0] t_reg_270;
wire   [63:0] zext_ln296_1_fu_178_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln295_fu_163_p1;
reg   [2:0] j_fu_46;
wire   [2:0] k_8_cast_cast_fu_141_p1;
wire   [2:0] add_ln295_fu_183_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_j_2;
reg    R_ce1_local;
reg    R_we0_local;
reg    R_ce0_local;
reg    x_ce1_local;
reg    x_we0_local;
reg    x_ce0_local;
wire   [3:0] mul_ln296_cast_fu_145_p1;
wire   [3:0] zext_ln296_fu_168_p1;
wire   [3:0] add_ln296_fu_172_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 j_fu_46 = 3'd0;
#0 ap_done_reg = 1'b0;
end

ukf_accel_step_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter21_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln295_fu_157_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_46 <= add_ln295_fu_183_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_46 <= k_8_cast_cast_fu_141_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_addr_reg_221 <= zext_ln296_1_fu_178_p1;
        R_addr_reg_221_pp0_iter1_reg <= R_addr_reg_221;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        x_addr_reg_227 <= zext_ln295_fu_163_p1;
        x_addr_reg_227_pp0_iter1_reg <= x_addr_reg_227;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        R_addr_reg_221_pp0_iter10_reg <= R_addr_reg_221_pp0_iter9_reg;
        R_addr_reg_221_pp0_iter11_reg <= R_addr_reg_221_pp0_iter10_reg;
        R_addr_reg_221_pp0_iter12_reg <= R_addr_reg_221_pp0_iter11_reg;
        R_addr_reg_221_pp0_iter13_reg <= R_addr_reg_221_pp0_iter12_reg;
        R_addr_reg_221_pp0_iter14_reg <= R_addr_reg_221_pp0_iter13_reg;
        R_addr_reg_221_pp0_iter15_reg <= R_addr_reg_221_pp0_iter14_reg;
        R_addr_reg_221_pp0_iter16_reg <= R_addr_reg_221_pp0_iter15_reg;
        R_addr_reg_221_pp0_iter17_reg <= R_addr_reg_221_pp0_iter16_reg;
        R_addr_reg_221_pp0_iter18_reg <= R_addr_reg_221_pp0_iter17_reg;
        R_addr_reg_221_pp0_iter19_reg <= R_addr_reg_221_pp0_iter18_reg;
        R_addr_reg_221_pp0_iter20_reg <= R_addr_reg_221_pp0_iter19_reg;
        R_addr_reg_221_pp0_iter21_reg <= R_addr_reg_221_pp0_iter20_reg;
        R_addr_reg_221_pp0_iter2_reg <= R_addr_reg_221_pp0_iter1_reg;
        R_addr_reg_221_pp0_iter3_reg <= R_addr_reg_221_pp0_iter2_reg;
        R_addr_reg_221_pp0_iter4_reg <= R_addr_reg_221_pp0_iter3_reg;
        R_addr_reg_221_pp0_iter5_reg <= R_addr_reg_221_pp0_iter4_reg;
        R_addr_reg_221_pp0_iter6_reg <= R_addr_reg_221_pp0_iter5_reg;
        R_addr_reg_221_pp0_iter7_reg <= R_addr_reg_221_pp0_iter6_reg;
        R_addr_reg_221_pp0_iter8_reg <= R_addr_reg_221_pp0_iter7_reg;
        R_addr_reg_221_pp0_iter9_reg <= R_addr_reg_221_pp0_iter8_reg;
        add38_i_reg_260 <= grp_fu_383_p_dout0;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        mul37_i_reg_245 <= grp_fu_387_p_dout0;
        mul42_i_reg_250 <= grp_fu_393_p_dout0;
        mul43_i_reg_255 <= grp_fu_914_p_dout0;
        rkj_reg_233_pp0_iter2_reg <= rkj_reg_233;
        rkj_reg_233_pp0_iter3_reg <= rkj_reg_233_pp0_iter2_reg;
        rkj_reg_233_pp0_iter4_reg <= rkj_reg_233_pp0_iter3_reg;
        sub_i_reg_265 <= grp_fu_906_p_dout0;
        t_reg_270 <= grp_fu_397_p_dout0;
        x_addr_reg_227_pp0_iter2_reg <= x_addr_reg_227_pp0_iter1_reg;
        x_addr_reg_227_pp0_iter3_reg <= x_addr_reg_227_pp0_iter2_reg;
        x_addr_reg_227_pp0_iter4_reg <= x_addr_reg_227_pp0_iter3_reg;
        x_addr_reg_227_pp0_iter5_reg <= x_addr_reg_227_pp0_iter4_reg;
        x_addr_reg_227_pp0_iter6_reg <= x_addr_reg_227_pp0_iter5_reg;
        x_addr_reg_227_pp0_iter7_reg <= x_addr_reg_227_pp0_iter6_reg;
        x_addr_reg_227_pp0_iter8_reg <= x_addr_reg_227_pp0_iter7_reg;
        x_addr_reg_227_pp0_iter9_reg <= x_addr_reg_227_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rkj_reg_233 <= R_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter22 == 1'b1))) begin
        R_ce0_local = 1'b1;
    end else begin
        R_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_ce1_local = 1'b1;
    end else begin
        R_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter22 == 1'b1))) begin
        R_we0_local = 1'b1;
    end else begin
        R_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln295_fu_157_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter21_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_2 = k_8_cast_cast_fu_141_p1;
    end else begin
        ap_sig_allocacmp_j_2 = j_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        x_ce0_local = 1'b1;
    end else begin
        x_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_ce1_local = 1'b1;
    end else begin
        x_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        x_we0_local = 1'b1;
    end else begin
        x_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign R_address0 = R_addr_reg_221_pp0_iter21_reg;

assign R_address1 = zext_ln296_1_fu_178_p1;

assign R_ce0 = R_ce0_local;

assign R_ce1 = R_ce1_local;

assign R_d0 = t_reg_270;

assign R_we0 = R_we0_local;

assign add_ln295_fu_183_p2 = (ap_sig_allocacmp_j_2 + 3'd1);

assign add_ln296_fu_172_p2 = (mul_ln296_cast_fu_145_p1 + zext_ln296_fu_168_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_383_p_ce = 1'b1;

assign grp_fu_383_p_din0 = rkj_reg_233_pp0_iter4_reg;

assign grp_fu_383_p_din1 = mul37_i_reg_245;

assign grp_fu_383_p_opcode = 2'd0;

assign grp_fu_387_p_ce = 1'b1;

assign grp_fu_387_p_din0 = mul3425_i;

assign grp_fu_387_p_din1 = x_q1;

assign grp_fu_393_p_ce = 1'b1;

assign grp_fu_393_p_din0 = div22_i;

assign grp_fu_393_p_din1 = x_q1;

assign grp_fu_397_p_ce = 1'b1;

assign grp_fu_397_p_din0 = add38_i_reg_260;

assign grp_fu_397_p_din1 = div22_i;

assign grp_fu_906_p_ce = 1'b1;

assign grp_fu_906_p_din0 = mul42_i_reg_250;

assign grp_fu_906_p_din1 = mul43_i_reg_255;

assign grp_fu_906_p_opcode = 2'd1;

assign grp_fu_914_p_ce = 1'b1;

assign grp_fu_914_p_din0 = mul3425_i_in;

assign grp_fu_914_p_din1 = R_q1;

assign icmp_ln295_fu_157_p2 = ((ap_sig_allocacmp_j_2 == 3'd3) ? 1'b1 : 1'b0);

assign k_8_cast_cast_fu_141_p1 = k_8_cast;

assign mul_ln296_cast_fu_145_p1 = mul_ln296;

assign x_address0 = x_addr_reg_227_pp0_iter9_reg;

assign x_address1 = zext_ln295_fu_163_p1;

assign x_ce0 = x_ce0_local;

assign x_ce1 = x_ce1_local;

assign x_d0 = sub_i_reg_265;

assign x_we0 = x_we0_local;

assign zext_ln295_fu_163_p1 = ap_sig_allocacmp_j_2;

assign zext_ln296_1_fu_178_p1 = add_ln296_fu_172_p2;

assign zext_ln296_fu_168_p1 = ap_sig_allocacmp_j_2;

endmodule //ukf_accel_step_ukf_update_3_2_2_Pipeline_VITIS_LOOP_295_3
