// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ukf_accel_step_ukf_update_3_2_2_Pipeline_VITIS_LOOP_350_16_VITIS_LOOP_351_17 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        S_out_address0,
        S_out_ce0,
        S_out_we0,
        S_out_d0,
        R_address0,
        R_ce0,
        R_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] S_out_address0;
output   S_out_ce0;
output   S_out_we0;
output  [31:0] S_out_d0;
output  [3:0] R_address0;
output   R_ce0;
input  [31:0] R_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln350_fu_106_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] add_ln351_1_fu_179_p2;
reg   [3:0] add_ln351_1_reg_260;
wire   [31:0] bitcast_ln351_fu_230_p1;
wire   [63:0] zext_ln351_3_fu_205_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln351_2_fu_226_p1;
reg   [1:0] j_fu_50;
wire   [1:0] add_ln351_fu_210_p2;
wire    ap_loop_init;
reg   [1:0] i_fu_54;
wire   [1:0] select_ln350_1_fu_149_p3;
reg   [3:0] indvar_flatten13_fu_58;
wire   [3:0] add_ln350_1_fu_112_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten13_load;
reg    R_ce0_local;
reg    S_out_we0_local;
reg    S_out_ce0_local;
wire   [0:0] icmp_ln351_fu_135_p2;
wire   [1:0] add_ln350_fu_129_p2;
wire   [3:0] p_shl5_fu_161_p3;
wire   [3:0] zext_ln351_fu_157_p1;
wire   [1:0] select_ln350_fu_141_p3;
wire   [3:0] sub_ln351_fu_169_p2;
wire   [3:0] zext_ln351_1_fu_175_p1;
wire   [3:0] p_shl_fu_185_p3;
wire   [3:0] sub_ln351_1_fu_193_p2;
wire   [3:0] add_ln351_2_fu_199_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 j_fu_50 = 2'd0;
#0 i_fu_54 = 2'd0;
#0 indvar_flatten13_fu_58 = 4'd0;
#0 ap_done_reg = 1'b0;
end

ukf_accel_step_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_54 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_54 <= select_ln350_1_fu_149_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln350_fu_106_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten13_fu_58 <= add_ln350_1_fu_112_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_58 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_50 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_50 <= add_ln351_fu_210_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln351_1_reg_260 <= add_ln351_1_fu_179_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_ce0_local = 1'b1;
    end else begin
        R_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        S_out_ce0_local = 1'b1;
    end else begin
        S_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        S_out_we0_local = 1'b1;
    end else begin
        S_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln350_fu_106_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten13_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten13_load = indvar_flatten13_fu_58;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign R_address0 = zext_ln351_3_fu_205_p1;

assign R_ce0 = R_ce0_local;

assign S_out_address0 = zext_ln351_2_fu_226_p1;

assign S_out_ce0 = S_out_ce0_local;

assign S_out_d0 = bitcast_ln351_fu_230_p1;

assign S_out_we0 = S_out_we0_local;

assign add_ln350_1_fu_112_p2 = (ap_sig_allocacmp_indvar_flatten13_load + 4'd1);

assign add_ln350_fu_129_p2 = (i_fu_54 + 2'd1);

assign add_ln351_1_fu_179_p2 = (sub_ln351_fu_169_p2 + zext_ln351_1_fu_175_p1);

assign add_ln351_2_fu_199_p2 = (sub_ln351_1_fu_193_p2 + zext_ln351_fu_157_p1);

assign add_ln351_fu_210_p2 = (select_ln350_fu_141_p3 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln351_fu_230_p1 = R_q0;

assign icmp_ln350_fu_106_p2 = ((ap_sig_allocacmp_indvar_flatten13_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln351_fu_135_p2 = ((j_fu_50 == 2'd3) ? 1'b1 : 1'b0);

assign p_shl5_fu_161_p3 = {{select_ln350_1_fu_149_p3}, {2'd0}};

assign p_shl_fu_185_p3 = {{select_ln350_fu_141_p3}, {2'd0}};

assign select_ln350_1_fu_149_p3 = ((icmp_ln351_fu_135_p2[0:0] == 1'b1) ? add_ln350_fu_129_p2 : i_fu_54);

assign select_ln350_fu_141_p3 = ((icmp_ln351_fu_135_p2[0:0] == 1'b1) ? 2'd0 : j_fu_50);

assign sub_ln351_1_fu_193_p2 = (p_shl_fu_185_p3 - zext_ln351_1_fu_175_p1);

assign sub_ln351_fu_169_p2 = (p_shl5_fu_161_p3 - zext_ln351_fu_157_p1);

assign zext_ln351_1_fu_175_p1 = select_ln350_fu_141_p3;

assign zext_ln351_2_fu_226_p1 = add_ln351_1_reg_260;

assign zext_ln351_3_fu_205_p1 = add_ln351_2_fu_199_p2;

assign zext_ln351_fu_157_p1 = select_ln350_1_fu_149_p3;

endmodule //ukf_accel_step_ukf_update_3_2_2_Pipeline_VITIS_LOOP_350_16_VITIS_LOOP_351_17
